### ISSUE TITLE
Auto-population of data fields in Jekyll data documentation

### ISSUE THREAD

**Issue by NealHumphrey** [codefordc/housing-insights#105]
We want a jekyll data sources page (e.g. /docs/data/example.md) to automatically pull in and list the information from meta.json into a human readable format. 

The documentation of our Github Pages currently has one page for each table of the database. 

- Top section is narrative, describing the data source and linking to other web information on the file. This is created manually by the data team when adding a new data source. 
- Bottom section needs to use the [Data Files](https://jekyllrb.com/docs/datafiles/)  feature of Jekyll to read in our meta.json and automatically pull in data field names and descriptions using the 'display_name' and 'display_text' fields. At the top of each markdown file, add a varaible to the YAML frontmatter called table_name. This can connect the page to the right portion of the meta.json. 

- Long term, our data update weekly script can also add additional stats to the meta.json such as most recent date, number of records, etc. (not needed now).

**Comment by NealHumphrey** [comment]
It seems like the best thing to do with this will be to create a /documentation folder on the Github Pages site. We should have one page for each table of the database. 

- Top section is narrative, describing the 
- Bottom section uses the [Data Files](https://jekyllrb.com/docs/datafiles/)  feature of Jekyll to read in our meta.json and automatically pull in data names and descriptions using the 'display_name' and 'display_text' fields. Long term, we can add extra stuff (like number of records in a table) to the meta.json via Python scripts during ingestion. 
- Use if statements to add additional stuff to the display_text

**Comment by NealHumphrey** [comment]
Neal set up a rough framework in /docs/data, which has been merged into /master and /dev. The automatic population of meta.json needs to be added to this.

**Comment by NealHumphrey** [comment]
@louvis This is the ticket I was talking about on Tuesday - let me know if you take it on!

**Comment by louvis** [comment]
@NealHumphrey thanks for pointing me to it. I'll try and dig into it and make some progress as I work through on the visualizations.
