### ISSUE TITLE
Competitive analysis

### ISSUE THREAD

**Issue by thischrisoliver** [codefordc/housing-insights#114]

**Comment by NealHumphrey** [comment]
Here's the stuff we have previously collected!
http://housinginsights.org/resources/inspiration

**Comment by thischrisoliver** [comment]
Here's the link to the Google Sheet that Krissy created for documenting our research: https://docs.google.com/spreadsheets/d/1kmrCwlBp5AHGy7yVHeL8XN8oQrX_2GB941mLOaqBnCI/edit?usp=sharing

**Comment by joawu** [comment]
I'm going to take a look at the Pres Cat and the DataKind neighborhood indicators data viz!
