### ISSUE TITLE
Create evaluator persona

### ISSUE THREAD

**Issue by thischrisoliver** [codefordc/housing-insights#127]

**Comment by NealHumphrey** [comment]
@thischrisoliver What's the status of this and any other persona tickets? Do we have usable versions that I can add to our /resources documentation page to link to?

**Comment by thischrisoliver** [comment]
The evaluator persona is incomplete right now because there just weren't really any trends I could pull from the interviews. I'm going to (maybe this weekend?) make a proto-persona based on assumptions I can make from what information we do have.

I'm also planning to (again maybe this weekend?) flesh out the Policy Maker, Policy Advocate, Tenant Advocate, and Developer a little more, explaining what each role does so that new recruits can get up to speed faster. However, there are versions on Google Drive that you should be able to use for now:

https://drive.google.com/open?id=0B-7k7TLmdLTaNnN3ZHZtVFVhYzA
