### ISSUE TITLE
Review data requests

### ISSUE THREAD

**Issue by thischrisoliver** [codefordc/housing-insights#129]
Review the Grouped sheet of Joanne's new data requests spreadsheet and mark off what data we have access to now, what we might be able to get access to at some point, and what we're probably never going to get.

https://drive.google.com/file/d/0B6iVubS2zjk4bFpOV3Q0RndQSk0/view?usp=sharing

**Comment by joawu** [comment]
Updated data request tally spreadsheet here: https://drive.google.com/open?id=0B6iVubS2zjk4dTRzR0J4aDBuZ00

- Feel free to change the grouping of data as you see fit. 
- Formatting is funky right now, but once all the data is in I can make a nicely formatted pivot table

**Comment by NealHumphrey** [comment]
This will be done by tomorrow morning! @joawu let me know if that's still the most recent version
