### ISSUE TITLE
HPTF Audit - investigate atudit report for data sources

### ISSUE THREAD

**Issue by NealHumphrey** [codefordc/housing-insights#131]
[This WAPO article](https://www.washingtonpost.com/local/dcs-affordable-housing-program-has-been-mismanaged-according-to-city-auditors-report/2017/03/16/42038e86-09b3-11e7-93dc-00f9bdd74ed1_story.html?utm_term=.4780e3e41fa7) summarizes findings from an audit of the housing production trust fund. We should read the original source report, summarize findings on our own, and see if it looks like the auditors may have any data available that we can use in housing insights. 

Should also see what this means in terms of data quality of the HPTF annual reports that we are extracting spending data from.

**Comment by jalbertbowden** [comment]
http://www.dcauditor.org/HPTF

**Comment by NealHumphrey** [comment]
Added note about this report to the documentation of the DHCD database.
