### ISSUE TITLE
DMPEDs Real Estate Projects Pipeline data

### ISSUE THREAD

**Issue by NealHumphrey** [codefordc/housing-insights#137]
DMPED maintains a [real estate project pipeline](https://octo.quickbase.com/db/bgk8b4c4n) database that is accessible through quickbase. They also summarize the information obtained both there, in DHCD's quickbase database, and the Inclusionary Zoning projects on an [affordable housing dashboard](http://open.dc.gov/economic-intelligence/affordable-production-preservation.html). 

Notes: 
- Quickbase data can be downloaded manually. I have downloaded a version (on 3/20/2017) and saved this to the /data/raw/dmped_project_pipeline_db/20170320  folder. 
- Quickbase data has more than just housing projects. But, the downloaded version is not clear what category of project they are unless it can be guessed from the project name (e.g. "Fort Lincoln Multifamily" or "Franklin School"). 
- Quickbase has an API (see issue #136 for related usage). But, it looks like the DMPED version requires an API key. Need to obtain one if we are going to include this programatically. 
- The dashboard code is [open source on Github](https://github.com/DCgov/economic-intelligence/blob/gh-pages/affordable-production-preservation.html) 
- The housing units data (attached to project name) is available [on Github here](https://github.com/DCgov/economic-intelligence/blob/gh-pages/assets/data/affhousing-st.csv). It's not clear how this file is updated (manually? automatically?). 

We want to be able to incorporate all affordable housing projects funded by the city. We want to integrate DMPED's database, as well as find out which of their data overlaps with other data (such as our IZ scraping from the office of zoning and the DHCD pipeline database). 

- [ ] Talk to someone at DMPED (Andrew Trueblood or Marie Whittaker) about the dashboard. Find out how data is updated, what it covers/doesn't cover, and how we can most effectively tap into this data. 
- [ ] Integrate this data into our ingestion process either via quickbase API (build off of #136) or reusing DMPED's scraping methodology.

**Comment by NealHumphrey** [comment]
@emkap01 and @salomoneb, this ticket plus #136 fit well with what you all have started on the PUD stuff. It might be good for one/both of you to take ownership of the whole topic of integrating city records of affordable housing spending, since there seems to be partially overlapping information. It's probably going to take a few conversations with people at the city to sort out what's what - DMPED staff noted above are probably the best place to start. Note, Andrew Trueblood recently responded to a Code forDC tweet about this project, pointing us towards these city databases. 

Related tickets: 
- #131 - Audit of the Housing Production Trust Fund
- #136 - DHCD's Pipeline Database
- #90 - PUD units from covenants
- #77 - extract data form HPTF reports
- #107  - comparing building name / address for dedup

@NoMoreOreo, @heysol you should also pay attention to this issue too.

**Comment by emkap01** [comment]
OK. I will compare what DMPED already has in their AH dashboard against the data outlined in the 5 tickets above.  Once we have a good idea of the overlap (and the delta), I'll reach out via email and copy @NealHumphrey plus the rest of the data team.

**Comment by emkap01** [comment]
Unfortunately neither the dashboard nor the GitHub repo offer any real granularity as to what AH data DMPED used, or where they sourced it from.  So figuring out "overlap" may not be possible, but I can still come up with a short list of questions we can ask them based on the 5 tickets above.

**Comment by NealHumphrey** [comment]
@emkap01 and @ehenry2172 - I got on the phone today w/ Marie Whittaker (@mseew) at the Deputy Mayor for Planning and Economic Development (DMPED). She manages the Economic Intelligence Dashboard](open.dc.gov/economic-intelligence/affordable-production-preservation.html). She gave me some useful insights into the various sources of data on DC affordable housing available. Here's a summary:

DMPED manages a Quickbase database that pulls from the DMPED, DHCD, DCHFA and DCHA data (some from the APIs mentioned in this ticket and #136, some from manual sources). They've put that data from the affordable housing database onto opendata.dc.gov

Some notes on the [Affordable Housing data source](http://opendata.dc.gov/datasets/affordable-housing) opendata.dc.gov  dataset scope:
- Includes All units from the DMPED, DHCD, DCHFA and DCHA lists since 2015
- Includes Inclusionary Zoning units since 2015
- Does not include units from the [ADU program](https://dhcd.dc.gov/service/affordable-dwelling-units). These are typically units that went through PUD process outside of the [IZ prorgam](https://dhcd.dc.gov/service/inclusionary-zoning-affordable-housing-program). 
- Fields include address and # of affordable units.
- Unit breakdown by AMI requirement is not included, but @mseew says she can probably have this added to the opendata.dc.gov data. 
- Loan amount information is not included. DHCD does publish this through their Quickbase api (#136) but if we want this for buildings in other agencies we'd need to investigate. 
- DMPED updates the master database monthly, and opendata.dc.gov gets a pull monthly, so it will probably be between 1 and 2 months behind. 

To get buildings pre-2015:
- Could definitely get a 1 time pull of DMPED projects before 2015 from @mseew
- DHCD - quickbase database has data starting Oct 2010; would need to talk to DHCD about earlier
- DCHFA - Marie will send contact for data person
- DCHA - Marie will send contact for data person

Based on this, I think the best course of action is to put a hold on this ticket and on #136 and prioritize linking the opendata.dc.gov dataset to the preservation catalog. Then we can decide how many of these other data sources we want to track down to get additional data (like loan information, etc.).

**Comment by NealHumphrey** [comment]
Closing this issue in favor of other relevant issues. I moved the background information about these buildings into our /docs/data portion of the website.
