### ISSUE TITLE
Zillow data added to AWS Postgres

### ISSUE THREAD

**Issue by NealHumphrey** [codefordc/housing-insights#14]
Zillow provides average monthly rents by both neighborhood and zip code. We want an ingestion script to load the data into our Postgres database. 

- [x] Verify that [TOU](http://www.zillow.com/corp/Terms.htm) allow us to use the data for this site. See last sentence of 'Permissible Use' paragraph. 

- [x] Download the "ZRI Time Series: Multifamily, SFR, Condo/Co-op ($)" data by neighborhood and by zip code. Save to the /scripts/small_data folder. [Data source](http://www.zillow.com/research/data/#bulk)

- [x] Using code from #8 as a basis, make ingestion code reusable to be run with either the PresCat data, the Zillow data, or other CSV data. Add a manifest file that references the downloaded data. 

- [x] Run the script to upload the Zillow data as two tables (zip and neighborhood)

- [x] Make sure the script is reusable, so that the data can be replaced with updated data on a regular basis.

**Comment by NealHumphrey** [comment]
Note - current code (as of 11/1/2016 2pm) does not properly handle date parsing - added a custom date parser so that nulls would be handled properly, but it needs to also handle multiple date types e.g. y/m/d and m/d/y. currently those in y/m/d format are forced to null.

**Comment by NealHumphrey** [comment]
Also, data has been uploaded to database but the script needs to be re-run with current code, which forces column names to lowercase and replaces - with _ for easier SQL query building.

**Comment by NealHumphrey** [comment]
This is done except for the Terms of Use. I just want a second opinion on interpretation that we are OK to use this for this tool's purpose as long as we include citation. Post a comment with your thoughts!

**Comment by mdelcambre** [comment]
I am in full agreement. It specifically says it can be used for non-personal uses. And agree that the only requirement appears to be that you are citing the Zillow Group with your derivative works.
