### ISSUE TITLE
Exploratory Visualizations

### ISSUE THREAD

**Issue by NealHumphrey** [codefordc/housing-insights#141]
Make exploratory visualizations using drag and drop tools like Tableau. We will show these to users to find out what is actually most important for us to include in the tool. 

Starter list of exploratory visualizations to create

- How many units of subsidized affordable housing are there in DC? Slicing:
    - Slice by neighborhood / ward
    - Slice by bedroom mix
    - Slice by AMI served (data collection still in progress)
    - Compare to total housing units in geographical area (data collection needed - MAR?)
    - Note: still collecting data on units that are created by city programs. PresCat has federal. 

- Compare total number of units in the city to when each of their last subsidy is set to expire. What's the worst case scenario of declining units via subsidy expiration?

- Look at the buildings that have received HPTF funding. What characteristics to do they share? Look at the current RFP. What would their score have been per the RFP scoring criteria? How does that compare to the buildings that are expiring in the next year? How does it compare to buildings that were lost that year?

- Market rate rent trends across the city. What are general rent trends in different areas? When combined with subsidy expiration, which buildings are facing the most market pressure? How is this different than just looking at subsidy expiration? What if we add in building permits and PUD applications - how does this help us identify development hotspots and the subsidized buildings near them?

- Compare population growth to total unit count growth. Dig into ways to slice this vs. income, etc. 

- How is bedroom mix changing? How does this vary by neighborhood? Market rate vs. subsidized?

- Compare HUD fair market rent to actual market rent

- Where have we lost affordable housing? How much as been lost over the past few years? Data quality check - can we trust the 'inactive' category in PresCat to be a true representation of this?

**Comment by juliaall** [comment]
Just snooping around the Project and Subsidy tables a bit. I'll be doing a join and export that to Tableau public.

**Comment by emkap01** [comment]
I added some csvs to Drive that anyone can use for [creating custom polygon maps by Ward and by ANC in Tableau](https://drive.google.com/open?id=0B_asTpLdSlEwLTlYQ0c2RDJfa2M).

**Comment by louvis** [comment]
I'm working with the REAC Score data. I have some visualizations started in Tableau Public and hope to add some maps.

**Comment by NealHumphrey** [comment]
Hey all (@juliall, @emkap01, @louvis ) - send me links to your visualizations so I can have them pulled up for the Tuesday night demos!

**Comment by juliaall** [comment]
Hi Neal,

Unfortunately, I don't have anything to share. My db connection dropped at the last meeting, and I never made it a priority to get it fixed nor had time to look at the csvs loaded.

I cannot make it tonight, but am sure the visualizations look good thus far.

-Julia

**Comment by louvis** [comment]
Here's what I have so far: [Average REAC Scores by Ward](https://public.tableau.com/views/HousingInsightsVisualizations/AverageREACScorebyWard?:embed=y&:display_count=yes), [REAC Scores and Properties by Ward](https://public.tableau.com/views/HousingInsightsVisualizations/REACScoresandPropertiesbyWard?:embed=y&:display_count=yes), [REAC Score Property Map](https://public.tableau.com/views/HousingInsightsVisualizations/REACScorePropertyMap?:embed=y&:display_count=yes)

I was working to setup a custom polygon map like @emkap01 had provided but didn't get that far. Depending on when I leave work today I might be able to make a few edits.

**Comment by NealHumphrey** [comment]
Cool thanks @louvis. Looks like a good start.

Just a bit of feedback on next steps based on a quick glance: one thing to
consider would be putting a diverging color scheme on that REAC score map.
Specifically, a 59 or below is a failing score so might be worth sticking a
different color on that. When there are multiple inspections it might also
be interesting to do something other than averaging  - i.e. min score, max
score, or most recent score.

**Comment by joawu** [comment]
Here are some visualizations for the project.csv:

[Number of Expiring Units by Ward and Cluster](https://public.tableau.com/profile/publish/NumberofExpiringUnitsinEachWardandClusterproject_csv/NumberofExpiringUnitsinEachWardandCluster#!/publish-confirm)

[Expiring Subsidy Timeline](https://public.tableau.com/profile/publish/ExpiringSubsidyTimelineproject_csv/ExpiringSubsidyTimeline#!/publish-confirm)
Notes:
* Size of bar is proportional to the number of assisted units
* You can filter the number of assisted units on the right
* Hovering over the bars reveals a tooltip, which lists the project name. (Right now some of the project unit names are stars though so I think I messed something up)

**Comment by joawu** [comment]
[Buildings with Expiring Subsidies in Each Ward](https://public.tableau.com/profile/publish/BuildingswithExpiringSubsidiesinEachWardproject_csv/BuildingswithExpiringSubsidies#!/publish-confirm)

**Comment by Nunie123** [comment]
Below is the excel file I used to build a few visualizations (which I posted in Slack).  To get the data I ran the code in analysis.txt, which relied on tables built using the scripts in transformations.txt.

[hi_chart_prototypes.xlsx](https://github.com/codefordc/housing-insights/files/974026/hi_chart_prototypes.xlsx)

[transformations.txt](https://github.com/codefordc/housing-insights/files/974030/transformations.txt)
[analysis.txt](https://github.com/codefordc/housing-insights/files/974031/analysis.txt)
