### ISSUE TITLE
MVP: Integrating elements into a map-based minimum viable product

### ISSUE THREAD

**Issue by ptgott** [codefordc/housing-insights#143]
At the 21 March meeting we talked about producing a basic minimum viable product that we could easily extend with various data sets. Some of the work consists in stitching existing components together, and some requires adding some new features. Some requires work on the backend. 

We'll organize the stitching around the Map View (javascript/tool/map-view.html). The user will select from geographic aggregation types (neighborhood, ward, zip code...) and datasets (rent, crime...) to display. There will be a menu for aggregation type/region; a menu for datasets; a map (the existing Mapbox map in map-view.html); and a sidebar for aggregations (the existing sidebar in map-view.html).

There are five main tasks:
- [ ] Turning the building information page into a partial that hovers over the map view. Clicking on the hover panel brings the user to the building page. 
- [ ] A menu for aggregation/zone types that (a) change the data that display in the map and (b) change the aggregation charts in the side panel of the Map View.
- [ ] A menu for datasets (e.g. crime and rent) that (a) produces a heatmap of aggregate data across the Map View and (b) produces donut (and other?) charts of aggregates on a side view.
- [ ] Ensuring that names for fields are consistent across our queries and checking them against meta.json. (copy meta.json from the data folder to the javascript folder). Whenever a particular data field is displayed in a graphic, pull the 'display_name' and 'display_text' from the meta.json rather than hard-coding the data name directly. 
- [ ] (Neal) Getting data transposed into different formats, aggregation/zone types (e.g. neighborhood cluster level, zip code level)

Let me know if this all makes sense and feel free to adjust the wording of the features!

**Comment by NealHumphrey** [comment]
I added a slight clarification to the meta.json  bullet. 

I also put my name by the one that I'll work on (transposing zone-based data to different zones). I reached out to Peter Tatian on this as he does something similar in Neighborhood Info DC; I also think I have a good idea on how to do it using DC's Master Address Repository (i.e. using residential housing units as a proxy for population, since we have residential housing units at the exact-address granularity level so can wrap them up into any arbitrary zone type).

**Comment by ptgott** [comment]
Unless anyone else is already working on it, I'll start on integrating the building information page into the new layout (the first task).

**Comment by ostermanj** [comment]
Yeah, go for it!

**Comment by ptgott** [comment]
I've done some work on linking the Building Page to the Map View in #153 
### What I've done
1. I've done a bunch of minor whitespace changes. This is why the pull request might seem more extensive than it really is.
2. In building-map.js, the MapboxPortal constructor had assumed that buildingForPage would be assigned from the beginning of the script. I've changed this to assign buildingForPage based on a server request, which calls for a different organization. As a result I've refactored the file to do the same thing without a constructor. There's a small bit of repetition now.
3. building-map.js uses the query string to define the target building based on the code for parsing the query string in building-header.js.
4. Clicking on a building dot in the Map View brings up a tiny pop-up with a link to the building page.

### Suggestions for later
1. Popups within Mapbox (called with the mapbox.gl.Popup constructor) seem to disregard the z-index, and the larger popups I played with rendered below the information overlay. There's a risk that the overlay will obstruct the popups if we include enough information in them. This is why I've kept the popups tiny for now. Currently the overlay includes information about each building the user clicks on, so we could distribute the information so that there's a small link in the popup and more extensive details in the overlay.
2. I've kept the code in building-map.js for fetching data separate from the app.getData() code in housing-insights.js. This is because the app.getData() assumes that the data will be csv, whereas the Mapbox maps use geoJSON. We can reconsider this if you'd like!

**Comment by ostermanj** [comment]
Nice. I'll try to review later today. My laptop was locked in my wife's office all weekend. It's good to have it back :)

**Comment by ostermanj** [comment]
FYI I'm working on some changes to the map-view page, getting one layer to show at a time and, I hope, getting that layer to correspond to the pie charts on the right.

**Comment by ostermanj** [comment]
Pull request #158 
This PR does much of what's in the second checklist item for this issue.

—user can select one mapLayer at a time
—the sidebar header info changes according to which layer is selected
—the data and piecharts adjust depending on which layer is selected (working only for ward, tract, and zip)
—the piecharts adjust when user selects specific zone from the dropdown menu (working for wards, tracts, and zips)

**Still to do**

—map does not yet zoom according to which zone is selected
—getting neighborhood and zillow layers to integrate with the piechart data would take some manipulation or a different, joined, dataset. The current data has the Cluster_tr2000_name field, which lists several neighborhood names. To integrate with zillow and neighborhood mapLayers, we'd need to know which one exactly

**Comment by ostermanj** [comment]
Also still to do is to animate the change in the size of the piechart segments. To be done with a D3 tween transition of the paths' "d" attribute. Good examples out there.

**Comment by ptgott** [comment]
I'll do some work on the 'meta.json' bullet this weekend!

**Comment by ptgott** [comment]
I've started working on integrating the Amazon Web Services API into the front-end. This will give us a basis for incorporating conventions from meta.json into code for making and interacting with charts.

What I've done so far (it's still early days!) is in PR #160

It's important to note that the code is untested and waiting on clarification/change related to AWS (see below). We can keep this un-merged until we sort out these issues!

**What I've done**
1. Added a getAPIData() method to 'app' in housing-insights.js. The assumption here is that we'll send out a batch of asynchronous requests when/as the document loads, wait for the data to return, then load all assets that rely on the retrieved data objects. getAPIData() takes two arguments. One is an array of table names taken from the first-level keys of meta.json. The second is a callback for doing stuff with the data once it's ready to use. The way I've started to implement this is through a version of the code I've used for fetching data for Mapbox maps within the building information page.

2. I've added an APIDataObj constructor to housing-insights.js. When getAPIData() retrieves a data file, it adds a new APIDataObj to app.dataCollection. Using the constructor approach, we can add methods to each data object. I've written one that changes the JSON to geoJSON (so far written only with points in mind, rather than polygons or other forms). We can also use this constructor to draw from meta.json to get a given column's display name for Charts (not yet implemented).

3. I've started to incorporate getAPIData() into rich-map.js, which in the current PR is at around line 107. I've put all the map-creation code into a prepareMaps() function that I call as the callback for getAPIData().

**An AWS issue**
getAPIData() sends an XHR request to the Amazon AWS URL, e.g. 'https://zjlpq5zz7e.execute-api.us-east-1.amazonaws.com/test//raw?tablename=project'. 

I'm getting the error, ‘Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://zjlpq5zz7e.execute-api.us-east-1.amazonaws.com/test//raw?tablename=project. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).’

We'll need to work out this error before we can test the code in this PR.

**Other outstanding issues**
1. getAPIData() adds data objects to app.dataCollection using the table name as a key. We can change this to use a hash (the data ID, part of the code for app.getData()) if we want!

2. The approach to fetching data from the API that I've tried has not used the PubSub code that the Chart constructor uses. We can talk about integrating getAPIData with PubSub.

3. I wrote a getAPIData() as method independent of getData() for my own convenience. We'll need to talk about how getData() and getAPIData() relate to one another. Do we incorporate the functionality of one into the other? Keep them separate?

**Other things that are left to do**
1. Incorporate meta.json to provide the display_name within Chart.

2. Integrate the building information page with the new data fetching structure.

3. The ‘polygon’ geoJSON objects ('ward', 'tract'…) don't seem to be available from the new API yet, so we need to determine how to make them available before we can use only the AWS API for the map view page.

**Comment by NealHumphrey** [comment]
@ptgott This is great stuff! I haven't dug into code yet, just read your summary. 

1) @prisalex - I think the CORS issue can be fixed through a setting in AWS (that's how it works for getting files from S3, at least). 

2) Let's be sure to talk through API issues and approach on Tuesday. @ptgott - would be good to hear your thoughts on the best data format to return. For example on your other things issue 2, is it best to do an API call for each chart? for each layer of a chart (i.e. bus stops vs. metro stops)? one for the whole page? We can set this up however needed. 

3) For other thing number 3 (polygons) - would it be better to get these from S3 directly? Or from the API? I guess the API could just have a 'grab this file from s3' function - that would let us change where the file comes from if we move it without changing the API interface for how the front end accesses it. Probably better... 

We can talk through all this Tues

**Comment by NealHumphrey** [comment]
@ptgott  and @ostermanj  - I have added the 'crime' data set to the database. I also produced these three flat files as summary formats:
https://s3.amazonaws.com/housinginsights/processed/crime/ward_summary.csv
https://s3.amazonaws.com/housinginsights/processed/crime/census_tract_summary.csv
https://s3.amazonaws.com/housinginsights/processed/crime/nc_summary.csv
Unfortunately the crime data didn't come with zip code attached - we can get it via the block, but it requires a call to the Master Address Repository API from #149 which we haven't gotten to yet. 

We should discuss how to best serve this stuff to you guys. @prisalex 's API does not yet support querying anything other than 'whole table', but you should plan to get these from the API in the near term instead of from these flat files. We can use this as an example to talk through:
- best format for summaries like the above
- Asking for all crime events would often overload the browser. Do we want to limit to specific zoom levels? Or just not expect to provide raw data (just zone aggregates)?
- What type of filtering should we build into the MVP (time frame, crime type, etc) and where should that happen (client or server side)?

**Comment by prisalex** [comment]
@ptgott  @NealHumphrey CORS issue should be resolved with the API.  Try now and let me know if you still run into issues.  Eventually, we should lock down the allowed origins to what we expect but kept it open for now.

**Comment by ptgott** [comment]
It looks like the CORS issue has been resolved. I've made some tweaks to PR #160 to get the data to display in the map view.

**Comment by ptgott** [comment]
@ostermanj @NealHumphrey 

**Here are some thoughts on the API.**

Overall, it’d be great to do minimal data processing on the client side while also being able to make specific, standardized API requests that correspond to a shared resource (meta.json). This way we could use meta.json as a communication tool, making it clear to the team which charts are available (so that the only charts available are listed in meta.json). Also, as you say in point number 3 in yesterday's comment, it'd be nice to decouple the API URLs from the locations of the data file. We could then do things like include a table name as an argument in a constructor to reduce repetition in making queries.

**The comment re: crime**
1. As for formats, JSON is good for me. We can convert to geoJSON on the client side if data defaults to JSON and we want to use JSON for charts that don't require geoJSON. 

2. Zone aggregates works for me — so far we don’t have point layers in the map view other than the projects themselves. This seems okay if the tool is used for gauging different conditions (average rent, traffic or what have you) that surround the project. We could restrict point layers to fixed objects like buildings and metro stations (so we can calculate distance), and polygons to ambient conditions (aggregates of things like crime and rent). 

3. So far the client side does have to know about specific field names (e.g. in specifying fields from the ‘project’ table to display in rich-map.js), so I’m okay specifying field names when displaying crime data. We can work this into the API, specifying fields in the query (e.g. '?tablename = { name }, fields = { stringified array of fields}').

**Re: the API in general (the comment from two days ago)**
1. It would be good to have processing standardized across the content of the charts. For instance a ‘public_transit’ chart would be the only one where we’d have to distinguish between ‘bus stops’ and ‘metro stops’, so this is a case where I’d prefer to have two charts. This way we could include processing within a query, e.g. filtering by field.

2. I’d also prefer to get the polygons from the API, taking the API as a one-stop-shop for data. This is only because it would lead to less repetition in the code!

**Comment by ptgott** [comment]
I've done a bit more thinking about the datasets menu.

First, it'd be really straightforward to model the menu off of @ostermanj's menu for region layers.

Second, [this](https://www.mapbox.com/blog/introducing-geojson-vt/) page on the Mapbox website suggests that rendering massive FeatureCollections might be doable. @NealHumphrey have you tried out adding a Mapbox point layer based on the crime incidents dataset?

Third, for geoJSON FeatureCollections that are 'points', we could follow [this](https://www.mapbox.com/mapbox-gl-js/example/heatmap/) example to produce a heatmap.

Though since the datasts such as those for rent aren't available for geospatial points, we could use the region-based aggregates that are on S3 now and just gray out any links within the zoning menu that don't correspond to a zone for which we have data.

Also, to make adding Mapbox layers of color-coded regions based on the zone aggregates really simple, we could start with the geoJSON file for each zone (located in the 'javascript/tool/data' directory) and add the aggregates to the 'properties' object for each polygon.

What do you all think?

**Comment by NealHumphrey** [comment]
Copying this over from Slack, with @ptgott posted, so that we have relevant discussion in one place: 

Sorry for not being able to make it to yet another meeting! I’ve got time over the weekend to work on the alpha MVP. I’ve also left some thoughts regarding the stitching job in issue 143 (https://github.com/codefordc/housing-insights/issues/143), and show one way of implementing a standard set of API calls to fetch data in PR 160 (https://github.com/codefordc/housing-insights/pull/160). My view is that the datasets menu is the big hurdle between now and a rough-and-ready MVP. Once that’s done and we present the MVP, we can work on finer interactivity and animation tweaks and extend the Map View to cover a broader range of datasets.

From the data team, it’d be great to have (another?) two sample API endpoints, both of which return data that we can layer over the Map View through a 'datasets' menu. The first endpoint would return a JSON file for geospatial data (i.e. with lat and long values) that we can easily turn into a geoJSON FeatureCollection of the ‘Point’ type (you can format this as geoJSON if you’d like!). The second API endpoint would return at least one geoJSON polygon file for at least one zone type (ward, census tract…). For each Feature in the FeatureCollection, at least one property in the ‘properties’ object would be an aggregate of data that we can use to color-code the polygon. For example, querying ‘/rent/ward’ would return the ‘ward’ geojson file (similar to the one stored in javascript/tool/data), but with, say, ‘average_rent’ as a property of each Feature. This way we could add a Mapbox layer that gives each (in this case) ward polygon a different color based on its average rent. Since we may not have aggregates of a given dataset available for all zone types, we can just gray out the unavailable zones within the datasets menu.

If you’ve got suitable API endpoints ready to go, please let me know! Thanks.

**Comment by NealHumphrey** [comment]
@ptgott In response to your post from 4 days ago (sorry so late!!)

1) Yes, agreed on a quick copy of the zone menu to make a data menu
2) That link describing massive geojson rendering is impressive. I have not tried adding this to a mapbox point layer yet. Of course you can also see we now have server-side aggregation of counts by relevant zone available via the API, so for color coding it's straightforward. @ostermanj this is a good reference point to add to last nights discussion of 'how much data is too much' browser side. One thing we may want to do is break our API endpoint up into a very basic list-all (e.g. only return lat,lon, and crime_id) and then have a separate API endpoint for details (i.e. api endpoint supplies crime_id to get all fields for that record). 
3) Heatmap - interesting example. That could be cool, though I might put it as phase 2 - let's start with color coding polygons by zone (unless you think this example is easier/faster). 

last) on the 'properties' point, do you mean you think that, at least in the short term, the API should return a full geojson object with properties pre-populated? Or would you plug something like our current API endpoint (which contains zone-name and count) and the JS would swap out the geojson 'property'? I think you meant the former, which I can do in a quick and dirty way in the very short term (today) and then we can figure out a better more systematic way to do it (so you're not constantly reloading the same geojson path data when you toggle between two different data sources).

**Comment by NealHumphrey** [comment]
@ptgott and @ostermanj I updated the API endpoint for counts of unique entries to behave like this. Based on my discussion w/ John plus some thinking it seemed like the easiest way for you guys to be able to use the same code as you toggle between different zone types (which I called 'grouping' and 'group' in the endpoint, but can change that if needed). 

endpoint: `/api/crime/all/ward` (also works for building_permits, and for ward,neighborhoodcluster,anc,zipcode)
```
{
  "grouping": "ward", 
  "table": "crime",
  "items": [
    {
      "count": 5071, 
      "group": 1
    }, 
    {
      "count": 6896, 
      "group": 2
    }, 
    {
      "count": 1643, 
      "group": 3
    }, 
    {
      "count": 2999, 
      "group": 4
    }, 
    {
      "count": 4632, 
      "group": 5
    }, 
    {
      "count": 5986, 
      "group": 6
    }, 
    {
      "count": 4051, 
      "group": 7
    }, 
    {
      "count": 3707, 
      "group": 8
    }
  ]
}
@ptgott - let me know if you want another endpoint that gives the full shape file, but it seemed like you might be able to do something similar to what you did with APIDataObj

**Comment by NealHumphrey** [comment]
Edit - avoid zipcode for the moment as the crime dataset does not include zipcode (it will eventually, just gotta geocode it).

**Comment by NealHumphrey** [comment]
Final note, just a heads up that this is not currently deployed to the live database but will be shortly - gotta run out

**Comment by NealHumphrey** [comment]
Hey all, closing this issue since we have the basic map view deployed - but, there's lots of discussion in here that's still kinda relevant. Flagged it in #212
