### ISSUE TITLE
Access Census data via API instead of Fact Finder

### ISSUE THREAD

**Issue by NealHumphrey** [codefordc/housing-insights#152]
For now, we're using the American Fact Finder to download the tables we need manually. It would be better to get this via an API, so that a) we can add new data sources more quickly b) we can update the data each year a new version is released and c) we can make one big table of all census data instead of one table per data field (the way files are provided in fact finder)

Using the MarApiConn as a model, create a CensusApiConn class that can create two csv output tables for us to add to our database:
- [ ] census_data with all relevant data fields we want. Default behavior should be to return results for a hard coded fields list specified in the method (use the list in the example API call below to start). The user should be able to specify a list of api field names they want as an optional param to override default behavior
- [ ] A matching table with margin of error fields. Each of the variable names below (`B01003_001E`) has a matching field (typically something like `B01003001M`) that has the margin of error. This appears to follow the pattern of changing the last letter, but should do some additional checking and/or ask a DataAnalysis team member to do research to verify.
- [ ] A draft table_meta.json in the same format created by `/ingestion.functions.make_draft_json`. Use the results of the example 'name and description' API call below to fill in stuff like display name. If you are well enough versed in OOP, try to make this method relatively DRY by adding a generic make_draft_json to the BaseApiConn, and then extending it with a call to `super()` in an overriding CensusApiConn.make_draft_json. If you're not confident in how to do this, just write a stand-alone method on CensusApiConn. 

The census API documentation is a bit confusing but here's what I've found:

Example API call to get the three tables corresponding to rent data (lower, upper, median). Note, you can ask for multiple fields in one API call. First table listed is total population. 
`http://api.census.gov/data/2015/acs5?get=NAME,B01003_001E,B25057_001E,B25058_001E,B25059_001E&for=tract:*&in=state:11`

List of variable codes (combo of table ID and column ID). Use this to find what items to add under the 'get=' part of the api call:
http://api.census.gov/data/2015/acs5/variables.html

Codes to specify level of granularity (i.e. tract or city or state level aggregates): http://api.census.gov/data/2011/acs5/geo.html
Example params: `for=tract:*&in=state:11` (as in example above) gets all census tracts in DC (this is the main thing we want). 

Population projections
https://www.census.gov/data/developers/data-sets/popest-popproj.html

Example API call to get the name and description of a variable you've requested:
ACS: `http://api.census.gov/data/2015/acs5/variables/B25058_001E.json`
Decennial Census: `http://api.census.gov/data/2010/sf1/variables/H00010001.json`

Potential wrapper tool (not sure if it's necessary)
https://pypi.python.org/pypi/census

Tables: 
* B02001: race

**Comment by NealHumphrey** [comment]
Useful summary of geographic categories: http://www.caliper.com/Maptitude/Census2000Data/SummaryLevels.htm

**Comment by NealHumphrey** [comment]
Note, as of 4/6 Census sent an alert: 
"We are currently experiencing an extended interruption in service for the Census data API. We are working to resolve the issue and apologize for any inconvenience."

But, it looks like some endpoints are currently working - just a warning if you encounter unexplained service interrupitons.

**Comment by citizenrich** [comment]
Heyo. Wanted to document where we are with census API. Here's the code. Small issue at the end remains to be fixed, then functions created and tests written.

https://gist.github.com/citizenrich/75ea8e03bd61725a9219ddc2341a6a0b

**Comment by NealHumphrey** [comment]
Thanks @citizenrich! Appreciate the update. Looks like it's coming along!

Feel free to put this into a Work in Progress pull request  - this can allow line-item comments and such. 

A few additional bits of feedback based on a quick skim of the code, to think about incorporating as you work on next phase of this:

- Do look at the MarApiConn code structure - we'll want to wrap your functional approach up into an OOP approach. The motiviation for this is so that all of our API calling-code behaves the same when we switch from running the API code directly to automating it with a CRON job.
- BeautifulSoup parsing of the HMTL variables page is a useful add. But, I don't think we'll actually want to dump all the variables into a super wide table - for one, [Postgres has a limit](https://www.postgresql.org/about/) of 1600 columns per table; in addition it makes it difficult to find which data is actually useful. Let's keep the variable parser as a utility to get a list of table names (potentially for input validation?), but have the user supply the list of column names they actually want inserted into our table. 
- Would be great to add a bit more comments on intent of code to make it more accessible to a new user - e.g.  describing the difference between the four different 'param' variables, and a quick note on goal of each block of code.

**Comment by citizenrich** [comment]
Very small beginning here: https://github.com/codefordc/housing-insights/pull/281

**Comment by NealHumphrey** [comment]
@citizenrich is traveling. To get census data in before our June launch we should have someone else pick up where he left off. I'm updating status. 

Some additional information:
- Start w/ code in the PR #281 
- the opendata.py example in #286 is the best model to work from to make sure that the census class behaves the same as all the others. Make sure there's a get_data method with all the same params as that one, and that it treats file save locations in the same way. 
- Use the get_api_data.py file in /scripts to test it out. 
- The gist linked above has some code that uses beautiful soup to parse the available table / field names provided by census - might be useful for validation?

**Comment by NealHumphrey** [comment]
@ajhalani maybe this is one you could take on?

**Comment by ajhalani** [comment]
Will take over..

**Comment by ajhalani** [comment]
First PR for code to output files - https://github.com/codefordc/housing-insights/pull/306 for the data output code. 
I used list of fields from existing code @citizenrich wrote (Thank you!). If you could comment on the fields, there is no combined census_tract field I can find from census. 

Still pending - meta.json/manifest.csv and any code changes needed for loading the files.

**Comment by ajhalani** [comment]
Second PR for code to ingest the new files - https://github.com/codefordc/housing-insights/pull/308

Please review both PRs

**Comment by NealHumphrey** [comment]
Done! Thanks @ajhalani
