### ISSUE TITLE
Create wireframes for mobile searching/filtering flows

### ISSUE THREAD

**Issue by thischrisoliver** [codefordc/housing-insights#156]

**Comment by NealHumphrey** [comment]
I don't think we need mobile wireframes, just a bit of mild thought by the JS people implementing these pages about how to degrade gracefully.

**Comment by thischrisoliver** [comment]
I'd argue that the design of the layout and what features are included for mobile requires more than just mild thought. It's actually something we were giving a lot of thought to on the design team. That said, mobile accessibility would most likely best serve tenant advocates who need to look up information about a specific building, which isn't our top priority right now. I think it's something that should just be put on the back burner for the moment.
