### ISSUE TITLE
Sketch desktop screens for searching/filtering flows

### ISSUE THREAD

**Issue by thischrisoliver** [codefordc/housing-insights#157]

**Comment by thischrisoliver** [comment]
Here are the sketches of the mobile screens from last night if needed for reference:
![screens round 1a](https://cloud.githubusercontent.com/assets/22454900/24473360/0027e09a-1497-11e7-9e09-f8afc6ccb9a5.jpg)
![screens round 1b](https://cloud.githubusercontent.com/assets/22454900/24473366/003c3270-1497-11e7-8e8e-9cb1505a3de7.jpg)
![screens round 1c](https://cloud.githubusercontent.com/assets/22454900/24473363/00329314-1497-11e7-83ef-fad641e4e927.jpg)
![screens round 2a](https://cloud.githubusercontent.com/assets/22454900/24473361/0030f414-1497-11e7-9b1c-83f7d541030c.jpg)
![screens round 2b](https://cloud.githubusercontent.com/assets/22454900/24473364/0032c10e-1497-11e7-8c0e-fb170202df19.jpg)
![screens round 2c](https://cloud.githubusercontent.com/assets/22454900/24473362/00314d06-1497-11e7-8a69-20dd7c7f9d45.jpg)
![screens round 3](https://cloud.githubusercontent.com/assets/22454900/24473365/003630c8-1497-11e7-9eb2-44b6e08e6bc6.jpg)
![user flow 1](https://cloud.githubusercontent.com/assets/22454900/24473369/004ad014-1497-11e7-8d06-f40a37ebf6d2.jpg)
![user flow 2](https://cloud.githubusercontent.com/assets/22454900/24473368/0046d48c-1497-11e7-8c34-a3a8d92d7608.jpg)
![user flow 3](https://cloud.githubusercontent.com/assets/22454900/24473367/00458c3a-1497-11e7-9eda-d7ab100ca3e7.jpg)

**Comment by NealHumphrey** [comment]
Closing in favor of #171
