### ISSUE TITLE
Make encoding a param in the manifest.csv

### ISSUE THREAD

**Issue by NealHumphrey** [codefordc/housing-insights#169]
Different csv files can use different encodings. Currently, the code is set to use 'latin-1' for all files, which can provide the wrong results if the file is utf-8. 

In the DataReader.py file, the HIReader base class, the __iter__ method contains a `with open(encoding='latin-1')` . We should change this to be a user specified parameter in the manifest.csv, and allow the reader to use this param when it is provided the manifest_row dictionary. This will require the  DataReader class to implement a new __iter__ method

- [ ] update DataReader class
- [ ] update the make_draft_json to add an encoding field to the draft json
- [ ] manually add this new json field to all the existing tables in the table_meta.json

**Comment by speedyturkey** [comment]
I think I can help with this. It sounds like the manifest.csv should contain a value indicating which encoding a given file uses. Should latin-1 remain the default?

**Comment by speedyturkey** [comment]
Fixed by PR 189.
