### ISSUE TITLE
Allow optional columns in the table_meta so that cleaners can add new data fields

### ISSUE THREAD

**Issue by NealHumphrey** [codefordc/housing-insights#176]
We want to be able to specify columns in the table_meta.json file that don't need to exist in the source data CSV file. These can either be a) optional fields not present in all versions of the data  or b) fields that do not exist in the source data but are instead added during the data cleaning process (such as geocoding fields). 

- [x] Add a 'required_in_source' param to each field in the make_draft_json function, with its default value set to False. 
- [x] Every table should have an additional field called `unique_data_id`. The json for unique_data_id should look like:
    ```
        {
                "display_name": "Unique data ID",
                "display_text": "Identifies which source file this record came from",
                "source_name": "",
                "sql_name": "unique_data_id",
                "type": "text"
                "required_in_source": False
            },
    ```
 The default 'required_in_source' param should set to False (since unique_data_id is added during the ingestion process)

- [x] Update the DataReader to be able to handle fields that do not exist in the source CSV file. The 'do_fields_match' validation will need to be updated to make sure that all required fields are there, and that no unknown fields exist. 
- [x] All Cleaner functions should be able to fill in missing values with the appropriate null value. This method will need to be called in every cleaner subclass. The existing replace_nulls method will not work because it only handles dict keys that exist in the `row` variable - new keys will need to be added to the row for missing values. 
- [ ] Create an appropriate TestCleaner 

### Background:
Currently, the HISql class in `python/housinginsights/ingestion/SqlWriter.py` initializes `self.fields` to match all the fields listed in the meta (being renamed to table_meta) variable. Then, it automatically adds a unique_data_id field. The create_table class therefore makes a table with all the columns in the table_meta plus a unique_data_id column. 

Meanwhile, the CSVWriter class (in `/ingestion/CSVWriter`) is used to take the rows of clean data provided by the Cleaner subclasses. It always adds a unique_data_id to the existing row dictionary. The 'write' method can probably stay the same (ensuring that every row of data has its associated unique_data_id) but the __init__ method will need to be modified so that it uses the table_meta version of the sql_field instead of manually adding it. 

Finally, the DataReader expects the number of rows to always match the table_meta; it enforces this by rejecting the table if the fields don't match (using the do_fields_match method). The SQLWriter requires all fields of the processed pipe-delimited file that is bulk-inserted into the SQL table to have values for every column of the database tables with an appropriate null for any missing value.

**Comment by speedyturkey** [comment]
@NealHumphrey Can you clarify the second bulleted item in the TODO list for this issue:
 _Add an additional field to every draft_json output called unique_data_id, with its default 'required_in_source' param set to True (to indicate that it does not need to exist in the csv file)_

I am reading this as add a new attribute to each field for each datasource, called "required_in_source". This attribute will be written by make_draft_json going forward, with a default value of False.  In that case, why should the value for all existing fields be set to True?

Thanks!

**Comment by NealHumphrey** [comment]
See my edited version - hopefully it is more clear! I misstated the default value, it should be False. The purpose of this is that every table we ingestion should have a column that does not exist in the CSV file that is called unique_data_id. This goes along with moving how the unique_data_id is added as described in this part of the Background section: 

"...but the init method will need to be modified so that it uses the table_meta version of the sql_field instead of manually adding it."

**Comment by speedyturkey** [comment]
This is helpful, thanks. I have a WIP branch on my fork - shouldn't take too much more work. I'll coordinate with you on updates to meta.json, which are floating around due to my work on this issue and also issue 169.

**Comment by NealHumphrey** [comment]
@speedyturkey this all looks great. The one issue I found was that the new approach broke a few tests in test_ingestion.py. Your tests are good replacements for that, but we do want to run all the tests in case that's not the case. I'm hoping to add TravisCI to our Github account soon to better flag stuff like that. 

I'm merging in locally and will fix that up and push it back here.

**Comment by NealHumphrey** [comment]
@speedyturkey no action on your part - I'll fix the ingestion tests
