### ISSUE TITLE
Weighting of census tract data

### ISSUE THREAD

**Issue by NealHumphrey** [codefordc/housing-insights#180]
Weighting files for translating from census tract to the other zone types have been added to the /data/geographic_data/tract_weights folder. 

We are waiting on #152 and for a longer list of fields from the census data before we need to implement this.  

Notes from Peter Tatian, who provided the weights files:
-------------------------------------------------------------
A few things to note. For apportioning counts of people, housing units, etc., you want to use the popwt field. For example,
 
 
**Geo2000**|**Ward2012**|**Pop**|**Pieces\_tr00**|**Pop\_tr00**|**Pieces\_wd12**|**Pop\_wd12**|**Popwt**|**Popwt\_prop**
:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:
11001000100|Ward 2|4674|1|4674|25|63455|1|0.073658
11001000201|Ward 2|4467|1|4467|25|63455|1|0.070396
11001000202|Ward 2|3850|1|3850|25|63455|1|0.060673
11001000300|Ward 2|2028|2|5706|25|63455|0.355415|0.03196
11001000300|Ward 3|3678|2|5706|21|75335|0.644585|0.048822

This shows the share of the tract (Geo2000) that is in the ward. So, 100% of tract 11001000100 is in ward 2, but only 35.5% of tract 11001000300 is in ward 2. The remaining 64.5% of the tract is in ward 3. In this case you would be doing a weighted sum of the tract counts to get the ward level.
 
(The Popwt_prop field is used for taking a weighted average of a proportion, mean, or median. Generally, I don’t recommend doing this, but sometimes you may not have a choice if you can’t create what you need from counts.)
 
There are versions of the weight files for both 2000 and 2010 census tracts.
 
We use a version of neighborhood clusters in NeighborhoodInfo DC that is slightly different from the ones published on opendata.dc.gov. These clusters were based on 2000 census tracts and so are a cleaner aggregating data. This was the recommended approach of the state data center at the time.

**Comment by NealHumphrey** [comment]
@ajhalani I don't know why the data dissappeared from that folder (or maybe I wrote the ticket planning to sync it there but didn't...). In any case, I've re-uploaded the weighting files to S3. 

If you have the CLI tool set up, you can navigate to the /housing-insights/data folder and use this command: `aws s3 sync raw/geographic_data s3://housinginsights/raw/geographic_data --profile housinginsights --dryrun`. This should list the files it will download; you can then run the same command again without --dryrun. 

Or little easier, just download directly from these links:
[2010Track to 2000Cluster](https://s3.amazonaws.com/housinginsights/raw/geographic_data/Tract_weights/Wt_tr10_cltr00.csv)
[2010Track to 2012Ward](https://s3.amazonaws.com/housinginsights/raw/geographic_data/Tract_weights/Wt_tr10_ward12.csv]
[Data Dictionary](https://s3.amazonaws.com/housinginsights/raw/geographic_data/Tract_weights/Data%20dictionary.xls)

For now we are only using the 2010 census tract definitions for our census data so you don't need the other two files in the folder. 

Part 1 of this task is getting the data into the database by adding to meta, manifest, etc. 
Part 2 is we need to make API endpoints for weighting any field from the census table. Let's do this with a new API endpoint like this:

`@application.route('/api/census/<sql_column_name>/<grouping>', methods=['GET'])`
<grouping> can be any of 'ward', 'neighborhood_cluster' or 'census_tract'. Census_tract applies no weighting, while the other two apply appropriate weighting. Note we will need to differentiate between things that get added up (e.g. count of citizens under povery line) vs. things that need a weighted average (median rent). @MikeS-nth is looking into which additional census fields to add in #104 so hopefully by the time you get part 1 done we'll have the list of fields available. 

Hopefully that's enough - let me know if you have questions! I can help with any stage of this so if you just get the first part done and then don't have time to finish just let me know as soon as you can and I can pick up.

**Comment by ajhalani** [comment]
Thanks @NealHumphrey. I will be able to work on this during the weekend, can't spare time during the week. If that blocks someone else's development, maybe it would be better if someone else can help with this. If it can wait, will try to knock out this weekend.

**Comment by ajhalani** [comment]
For later reference - Good description of neighbourhood cluster and wards - 

**Neighborhood Clusters**
- Description - https://www.neighborhoodinfodc.org/nclusters/nclusters.html
- Visual mapping - http://neighborhoodinfodc.org/pdfs/Cluster_Tract.pdf
----------------------------
**2012 Council Wards**
- Description - https://www.neighborhoodinfodc.org/wards/wards.html
- Visual mapping - http://neighborhoodinfodc.org/pdfs/Ward_Tract.pdf

**Comment by ajhalani** [comment]
@NealHumphrey - can you help clarify - 

> Part 1 of this task is getting the data into the database by adding to meta, manifest, etc.

Do you mean just loading these tables? Any preferences on the name of table/column? 

> Part 2 is we need to make API endpoints for weighting any field from the census table. Let's do this with a new API endpoint like this:
@application.route('/api/census/<sql_column_name>/<grouping>', methods=['GET'])

I am not sure what this entails, is their any sample code which does this already so I can review to understand?

**Comment by NealHumphrey** [comment]
@ajhalani 
1) Yep, that's it. No particular preference on table/column names. But, do make sure that column names are universally unique to the database, i.e. the same column name doesn't exist in another table. While not required by SQL, this helps us w/ front end coding. It will probably happen naturally anyways. 

2) There are some similar endpoints in the `/python/api/application.py` file. Currently that is the only file used to make our API, so that is also the place you will add the code. To make a new endpoint, you add a new function somewhere in that file (near the end probably), and make sure to put the `@application.route` decorator above the function definition. The `def project_subsidies(nlihc_id):` method in line  511 is a good simple example that you could start from:

```
    conn = engine.connect()  #always make a new connection and close it at the end - this allows the API to keep running ifone connection fails. 
    proxy = conn.execute(q)         #Any SQL statement you want goes in the `q` variable. 
    results = [dict(x) for x in proxy.fetchall()]  #This produces a list of dictionaries where the dict keys are column names from the database - usually the most convenient way to get the database results. 
    conn.close()                            #Whenever you're done getting data out of the database.  You could run a second conn.execute() if you wanted before doing this. 
    output = {'items':results}        #This is the convention we're using for anything kind of output from an API that looks like a bunch of rows in a table - put the list of dictionaries into another dictionary with the key 'items'. 
    return jsonify(output)
```

To test locally, assuming you're doing everything inside docker, you simply run `python application.py` and then you will be able to browse to `localhost:5000` to view the api. The url pattern you put in the decorator determines your endpoint url. 

Let me know where you end up today. If you don't think you'll get to it by end of Monday evening I can help stick it in so that we can include this in the Tuesday launch.

**Comment by ajhalani** [comment]
@NealHumphrey  created PR for part 1, please review. 

Will start work on part 2 and provide update by EOD today.

**Comment by ajhalani** [comment]
@NealHumphrey I have made some progress in the api code, but it's not close to being completed. I will need few days to understand how to implement the maths behind weighting correctly for ward/clusters. Apologies!
