### ISSUE TITLE
Crime data via the opendata API

### ISSUE THREAD

**Issue by NealHumphrey** [codefordc/housing-insights#187]
We currently have crime data that is manually downloaded from the Crime Data Map. 
Opendata.dc.gov provides the same data via an API, and with extra geocoding data added to it (lat/lon etc.). It looks like the newly-updated opendata.dc.gov is now being updated daily with this info, so we should switch sources so we can keep getting new updates. 

- Create a CrimeApiConn class based on the MarApiConn class currently in the code. Use this to add raw data files to `/data/raw/crime/opendata/YYYYMMDD` when  the `python/cmd/data.py` script is run with the appropriate arguments. Write a demo command to run at the command line to create this file with the appropriate datestamp. 

- Run this for all of the past years of data (each year is a separate "dataset" on opendata.dc.gov). Follow the '[add a new data source](http://housinginsights.org/resources/adding-data-sources.html)' instructions. 

Future: automatically add new files to the pipeline whenever this update script is run, but we wait to do this until we have created an appropriate structure for all API scripts.

**Comment by just4jin** [comment]
in progress

**Comment by jasonrhaas** [comment]
I'm interested in improving the data ingestion automation process as well.  This issue and #198 seem to be related.  Both are using opendata.dc.gov, so I think that rather than generating custom data ingestions for each, we should have a more generalized approach for ingesting data from opendata.dc.gov.

I think that using the API is 100% the right approach, rather than manually downloading data.  Even better would be using a generalized python module for pulling data, to abstract out the differences between data sources.

For example, in the code we might have:

```
from dcdata import Crimes, Taxes

crimes = Crimes.pull()
taxes = Taxes.pull(year=2012)
```

And of course we can manipulate the data from there to get it into our future SQLAlchemy format.

**Comment by NealHumphrey** [comment]
@jasonrhaas Yes, it would be good to use the same approach - though part of breaking things up was to have things that multiple people could work on it once. 

@jkwening is leading up the Python side of the data ingestion code so he's the best one to coordinate with!

**Comment by NealHumphrey** [comment]
@ajhalani and @just4jin flagging an issue for you that came up in the tax ingestion. The json api's have a default limit of 1,000 records. Looks like the best solution is using the 'geojson' api endpoint, but swap .geojson for .csv to get a bulk download of all the api already in csv format.

**Comment by ajhalani** [comment]
Thanks Neal.

**Comment by ajhalani** [comment]
Work completed in PR - https://github.com/codefordc/housing-insights/pull/286

@NealHumphrey  can we close this?

**Comment by ajhalani** [comment]
Work completed in PR - https://github.com/codefordc/housing-insights/pull/297 to ingest csv that are dumped by OpendataApiConn classes.

**Comment by ajhalani** [comment]
The crime data can now be downloaded and ingested. @NealHumphrey  okay to close this story?

**Comment by NealHumphrey** [comment]
Yep! Thanks @ajhalani, closing issue

**Comment by NealHumphrey** [comment]
@emkap01 heads up that crime data is now working
