### ISSUE TITLE
Ingesting real_property file

### ISSUE THREAD

**Issue by kasao10** [codefordc/housing-insights#199]
Working to add real_property_Mar2017 to database.

housing-insights/data/raw/preservation_catalog/20170315

**Comment by kasao10** [comment]
@NealHumphrey I'm having trouble locating table_info.json.  Could you direct me?

**Comment by NealHumphrey** [comment]
I was too quick in renaming it in the instructions. In the current code it
is called meta.json. The confusion between meta and manifest is why we want
to rename, but it just hasn't happened yet.

**Comment by kasao10** [comment]
real_property dataset is ingested, and committed, although interestingly, there were no changes to the meta.json that were committed (so I assume the code was already in there).  

Documentation is still incomplete.
