### ISSUE TITLE
Map load listener not registered until after map is loaded

### ISSUE THREAD

**Issue by nealfwilliams** [codefordc/housing-insights#206]
After the initial api calls are made, a load event listener is registered on the mapbox map object.  However, currently the map sometimes loads before the api calls finish, so the callback is never called.  On my machine this seems to happen only when using chrome.

**Comment by NealHumphrey** [comment]
@ostermanj I'm closing this as a separate issue since I assume this will be handled differently in the refactor - but just a heads up for you!
