### ISSUE TITLE
Ajax API calls aren't given sufficient time to load

### ISSUE THREAD

**Issue by nealfwilliams** [codefordc/housing-insights#209]
The getInitialData function in housing-insights.js will stop checking for the requested data after x intervals of y milliseconds.  Right now x and y are set to 10 and 500, respectively.  On firefox, with my internet connection, this isn't always enough time to complete the requests.  Since we don't know what the internet connection will be like on Monday, these shouldn't probably be bumped up.

**Comment by NealHumphrey** [comment]
@nealfwilliams I see the two lines in housing-insights.js under the `getInitialData` function (line 116). Is that the only place that needs changing? Should I just bump the 10 up to something like 60 for safety? If it doesn't load in 30 seconds we've got bigger problems.

**Comment by nealfwilliams** [comment]
Yeah 60 should definitely make sense.  I can submit a PR for this.

**Comment by NealHumphrey** [comment]
No need, I'm doing clean up of some labeling and stuff so am adding it in
right now.

**Comment by NealHumphrey** [comment]
Implemented in launch
