### ISSUE TITLE
JUNE: Front-end Refactor

### ISSUE THREAD

**Issue by NealHumphrey** [codefordc/housing-insights#212]
General catch all to put things that would be good to make more systematic in the next version. @ptgott and @ostermanj feel free to add stuff as you come across it. 

- Overall look at our code structure - how do we feel about it? Can we do some things more consistently? For example, function declarations as variables vs. the app dictionary (esp. across multiple files), IIFE vs. chaining of functions, promises etc.
    - Example: building view page split between building-header, building-map, etc.
- How should we handle legends. Currently a very hacky method in the 'nearby transit' section. Mapbox has SVG icons or custom-drawn circles. One icon has SVG raw copy-pasted into the building page, the other icon is generated via a tiny D3 svg infill that has duplicated properties as to what was put in mapbox. What's the best way to do this more systematically? Can we create a legend function? 
- Pull some stuff into functions, for example duplicated bus vs. rail code. 
- What's the best way to make api calls that depend on other API calls? For example, nearbyHousing and nearbyPermits in the building-map.js depend on having the buildingLat and Lon. Currently I solved this by making the whole thing in building-map.js a function variable which I call in building-header.js (this should be refactored a bit).

**Comment by NealHumphrey** [comment]
Commenting on #2 - here's a demo of built in map-box legend, though we want to link ours out to other parts of the page too: https://www.mapbox.com/mapbox-gl-js/example/updating-choropleth/

**Comment by ptgott** [comment]
Here's one thing we can talk about adding to the list: changing the division of labor between front-end and back-end so that the choice of datasets to fetch and display is done on the back-end. This way we won't have to, for example, manually enter information about each API query into rich-map.js. What this would allow would, in theory, be more extensibility in adding datasets (e.g. over 10 datasets to choose from on the data menu, each with aggregates for different zone types). A page would send a query for, say, 'map-view', and the server would know what datasets to return. The JS would then render the datasets appropriately. One way to do this, speaking generally, might be to include metadata in each dataset regarding what pages that dataset would be used for, then have the server return a big JSON object stringing together all datasets to return for a particular page. What do you think?

**Comment by NealHumphrey** [comment]
@ptgott I think we probably don't want to totally push this onto the API, but I do think you're right that we need to build more flexibility into the front end and more uniformity into the back end, allowing the front end to render appropriately across different data sets using the same code. 

I'm concerned about future long-term performance implications of getting one big JSON object for each page. What if it is instead more user driven? Something like:
- Map view has two broad categories of data display types - "point" and "zone". API has one consistent endpoint for each of these two types that behaves the same for whichever data source is requested. Data display information like labels and descriptions are returned, even if they were encoded in the API request (for example in the 'nearest X building_permits endpoint, I return the distance in the data even though it was also part of the request). 
- Front end maintains a user-facing menu that is used to toggle data sets. This is the one DRY location that endpoint data, variable names, etc. are stored. 
- Clicking a data point queries the relevant API and adds it to the data queue. 

That way we still have to maintain a list of what data sources should be accessible to the user; but, we have consistent approach to using them, and one obvious place to make a list of everything needed to use them. We also don't slow down the page by loading data that we don't need, and those same API endpoints can be re-used for other more specific visualizations on other pages instead of duplicating endpoints. 

what do you think?

**Comment by ptgott** [comment]
That sounds good! Also, it might be good to stitch aggregate data together with polygon geojson for regions on the backend. For zone data the API could return only a geojson file that includes the relevant aggregates, an alternative to combining the aggregate json and the geojson on the front end after separate XHRs.

**Comment by NealHumphrey** [comment]
@ptgott, @ostermanj , @prisalex and I discussed options at last night's work session for how to approach refactoring the front end code to deal with these issues. The below sketch is what Paul and I sketched out at the end of the night per this discussion. 

Next steps: we proposed making a "hello world" version of this architecture, independent of our current code, to demo the interface that each of these code sections (most of them probably via objects) would have and how they'd talk to the other objects. Once we're satisfied that we have a structure that deals with the big problems we've identified, we'd switch over to implementing this for the real code. 

I know Paul was planning to take a stab at the hello world version, but I think that it might be good to have more than one person take a stab at it and compare the approaches. I suggest if anyone wants to work on any piece of this, push your code often and tag the rest of us with a work-in-progress pull request so that we can work collaboratively on this between now and next session. 

![20170418_220926](https://cloud.githubusercontent.com/assets/5642566/25185381/34abc570-24eb-11e7-8f0a-8b77b4e455de.jpg)

Main concepts: 
- every box on here is an object category, except page.js which is the IIFE for each specific page that selects the appropriate 'specific charts' and 'user selection components' (drop down menus etc. ) to put on the page.
- Each specific chart uses a reusable chart and a specific data set, stores all its customized attributes (colors, sizing, etc.) and can both draw the chart onto a specific html ID and create its legend objects wherever they are needed. 
- "chart 1" is a generic chart (i.e. "pie chart") that could be used with different data. I think it's probably a good idea to follow the guidance from Mike Bostock on [Towards Reusable Charts](https://bost.ocks.org/mike/chart/), specifically a closure with getter and setter methods that return the chart (to allow for method chaining). This will probably make the code in 'specific chart' easier to write. 
- Not shown here is the 'chart prototype' that is similar to what we have in the current housing-insights.js, though the data acquisition functions need to be instead moved into a data object prototype. 

This is all just a proposal - if you find issues with it or have different ideas, feel free to try them out.

**Comment by ptgott** [comment]
Oh aside from what I've mentioned in PR#226, when it comes time to implement the new organization of the JS files, it'd be good to set up some unit tests, just to make sure everything 'works' while we're moving the code around.

**Comment by NealHumphrey** [comment]
Flag - should review https://github.com/codefordc/housing-insights/issues/143 for a few relevant discussion topics that should be pulled into this refactor / next steps.

**Comment by NealHumphrey** [comment]
@ptgott and @ostermanj after playing with this some myself, I thought it might be useful to also consider the absolute-minimum refactor version so we can decide appropriate tradeoff. 

My thoughts about some minimum features:
- Wrap all charts into their own unifying function/object (or maybe append them to the `app` object, though this is where I ran into prototypical inheritance issues). This way when you include a js file like 'pie.js', it just loads the function - the 'mypage.js' file then has to execute that function (passing any necessary data arguments etc.)
- Use the same interface for all charts (we're close with the protypical chart for D3, but need to implement parallel approach for Mapbox). 
- Make sure each chart can return legend information when asked
- Make sure each chart can be subscribed to events (via pubsub) that execute its 'update' function. mypage.js is in charge of subscribing it (not pie.js itself). That means the same chart can be reused if needed (or, at a minimum, charts that aren't designed to be reusable still use the same interface as those that are). 
- Deal with how to handle data promises. Even if it's not ideal performance, for a working version we don't necessarily need to have data preserved if it's tricky - for example, we can re-hit the API 3 times if a user toggles between crime, building permits, and back to crime. Obviously better to keep it in memory but don't want to optimise code prematurely.

**Comment by ostermanj** [comment]
long note on status of my "option2" refactor over in PR #232

**Comment by ostermanj** [comment]
To update this issue: PR #253 continues option 2 refactor and has the data overlays working (crime and building permits) in a basic way, using the MVC format and the getData() method.

**Comment by ptgott** [comment]
@ostermanj @NealHumphrey 
I'm going to incorporate the front-end refactor with some bits of the latest Browse view front-end code (#237) tomorrow and maybe Friday, organizing this so the refactor (#253) becomes the default Javascript code base. Here's a list of specific plans. Let me know if there's anything else, or if you'd like to organize the work differently!

@NealHumphrey and I talked about pushing these changes into a PR on @ostermanj 's repo, keeping the changes away from housinginsights/dev until we're sure they're all okay. 

1. Move the refactor into the docs/tool/js. I'll merge move the js code from PR #261 into a temporary folder so I can incorporate features a little at a time into the refactor.
2. Edit meta.json to incorporate features of 'manifest' in the refactor and 'data_for_browse.json' in PR #261. I'll aim to do this in a way that anticipates possible changes in the API endpoints (e.g. returning a table of aggregates rather than counts). I imagine this step will depend #266, though I haven't looked this over.
3. Incorporate into the refactor: 
   - Check meta.json to see which zones are available with which dataset in the API. Populate the data menu accordingly.
   - While using the 'toDOM' functionality and component-based constructors from PR #261, keep both dataset and zone menus up at all times (unlike PR #261). When the user selects a dataset or a zone, it'll display unavailable counterparts in the other menu. This will involve a fixed array of zone types (in the refactor but not PR #261).
   - Incorporate from PR #261 the LayerOption constructor for producing Mapbox layers dynamically from indefinite datasets (we're still using the code to merge aggregates with geoJSON polygons on the front end).

**Comment by ostermanj** [comment]
This all sounds good! I may experiment with tangential things in the coming days like UI components and ideas for switching between views, but let me know if you want to divvy these tasks up at all.

**Comment by ptgott** [comment]
@ostermanj @NealHumphrey 
I've merged #291. Today I'm going to work on integrating the building view into the refactor.

**Comment by ptgott** [comment]
I've started moving Building Page stuff into the refactor in PR #298. While everything is mostly in the right place, I haven't even run the code yet. The plan is to debug it tomorrow. I also have to make sure that the JS for the Building Page is called in the right places/times.

**One thing to consider for later:** I've hardcoded the requests for default datasets in the Building View. This isn't very extensible or flexible. It'd be great to use meta.json instead. The only issue is that several of the required tables/fields aren't straightforwardly included within meta.json. At some point we can talk about how to make the requests for default/initial datasets less coupled to explicit calls in the JS.

**Comment by NealHumphrey** [comment]
@ptgott Sounds good! Note that I merged in @ostermanj 's fly-in sidebar code so you'll want to update your branch with the latest dev. 

On your comment on the Building View datasets - I think we don't want to use meta.json to provide the datasets, because we're doing more custom displays as you've noted. Unlike our main browse/filter page, we're deliberately choosing what things to put on the page and how to lay them out, rather than populating a user-selectable list of data choices. I think it's appropriate to hard code them. If we add new data sets, we'll need to choose which fields to put where so the DRY location of what data to include in the building view should be in the building view not on the API.

**Comment by ptgott** [comment]
@NealHumphrey @ostermanj 
I've done a bit more work in PR #298, which has been messier than expected. I've zapped some runtime errors, mostly related to matching up references to data with the data objects themselves. The subsidy timeline chart is beginning to emerge, though it's now hilariously off-kilter. I think a big part of this might be SubsidyTimelineChart.prototype.timeParser not matching up with the date format that the API endpoint returns.

I haven't made time yet to merge in the updates to the 'dev' branch, but will when I can!

**Comment by ptgott** [comment]
@NealHumphrey 
Is there anything left of this issue for post-version 1 work, or is it closed?

**Comment by NealHumphrey** [comment]
@ptgott We've done a lit of the big code stuff, but there's a few building-view specific items that are probably worth revisiting based on our single-page app design. I'll look through the code and rewrite this into a clean new ticket and/or discussion points for our planning sessions
