### ISSUE TITLE
Needed API endpoints for Monday demo

### ISSUE THREAD

**Issue by NealHumphrey** [codefordc/housing-insights#213]
- [x] Number of building permits within X miles of given latititude+longitude. Potential endpoint url using params? `/api/building_permits/<dist>?latitude=<latitude>&longitude=<longitude>`
    - see the `python/housinginsights/analysis/rough_nearby_building_permits.sql" query for a pre-filter query approach that filters lat/lon to those near enough to be considered 
    - Should make a mapping of  +- values based on requested distance to allow for larger distance so we can be sure to include all false positives
    - Use the haversine formula to calculate actual distance and filter out the false positives from the sql query. 
    - return list of dictionaries in the format `{ "items": [ {"permitnum":1234,"applicant":"bob"....}, {"permitnum": 2....}]}`. "items" format is used in the existing endpoints and allows us to add precalcualted summary stats later without altering the usage. 

- [x] Same as above but for affordable buildings in the projects table. 
    - Filter to only those with status='active'  (SQL where statement)
    - Also include sum of `proj_units_assist_max` of all entries e.g. `{"items": [list of record dicts], "tot_units": <sum_of_all_units>}`

**Comment by NealHumphrey** [comment]
@prisalex if you're interested in taking this on this weekend it'd be a big help! I'll look at it mid-day Sunday if no one has claimed it by then, shouldn't be too terribly difficult - just gotta add in an implementation of Haversine formula.

**Comment by ohaaga** [comment]
I made a draft PR in case nobody else bites.  Probably out of the loop tomorrow, or I'd offer to debug and test.  Break a leg on Monday.

**Comment by NealHumphrey** [comment]
@ohaaga awesome, thanks!

**Comment by NealHumphrey** [comment]
Deployed!
