### ISSUE TITLE
FileNotFoundError while running nosetest

### ISSUE THREAD

**Issue by terrysky18** [codefordc/housing-insights#235]
![nosetest error 2017-5-2](https://cloud.githubusercontent.com/assets/3409035/25641683/70fb8f56-2f63-11e7-8e13-f333cdad58a6.jpg)

While studying the current unit tests, I ran into this error.  Here is the error output.

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\UsersDirectory\\Repository\\housing-insights\\python\\housinginsights\\ingestion\\../../../data\\sample/project_sample.csv'

**Comment by dogtoothdigital** [comment]
Looks like it's probably specific to NTFS; couldn't replicate the error in my linux environment.
