### ISSUE TITLE
Produce list of filter criteria

### ISSUE THREAD

**Issue by Nunie123** [codefordc/housing-insights#236]
Being able to filter the result set of properties is a critical feature.  

In order to implement the filter feature, we need to decide on a list of criteria that the user will be able to filter on.  At this late stage of the project, we should limit our filter criteria to data that is currently ingested, or data that we expect to be ingested soon (consult with ingestion team).

Once we have decided on a list of criteria then the front end people can design and build the form, and the back end people can build the API.  This list will have a significant impact on the implementation and should be completed (at least preliminarily) before substantial effort is put into other parts of this feature.

**Comment by Nunie123** [comment]
Potential filter criteria:

- Type of subsidy
- Agency providing subsidy
- Subsidy start date
- Subsidy end date
- At risk of leaving program
- Number of units covered by subsidy
- Active vs. former subsidized properties
- REAC score
- Last inspection
- Last renovation
- Avg. rent by neighborhood/ward/census tract
- Higher vs. lower crime by neighborhood/ward/census tract
- neighborhood/ward/census tracts with rapidly increasing rent
- Distance to closest rail/bus stop.
- Distance to a particular rail line.

What else can people think of?

**Comment by NealHumphrey** [comment]
@Nunie123 - thanks for starting this! I suggest starting simple to get the ball rolling. The following fields are a) definitely available and b) definitely needed and c) represent a few different technical challenges for how the data is associated to a building. 

We will want more than this eventually, 

1) project -> 
This is the most simple filter, where one record means one project that is filtered in/out
- proj_units_tot
- proj_units_assist_max 
- hud_own_type
and 'geographical area':
- ward
- ANC
- geo2010 (will be renamed to census_tract)
- cluster_tr2000 (will be renamed to neighborhood_cluster)
- proj_zip (will be renamed to zip and current zip [which says things like "ZIP 20001"] will be named zip_string)

2) subsidy ->
project to subsidy is one to many. Want to return project records if ANY of the many subsidy records match criteria:
- poa_start  (this is subsidy start date, poa=period of affordability)
- poa_end
- portfolio (this is a higher-level 'type of subsidy')

3) census ->
Our 'acs_rent_median' table will soon be replaced instead with a 'census' table that includes records for ALL census fields (one of which will be acs_rent_median). When this is ready (after doing above) we'll want to add this as one example - but we will want to have many options. 

"in a census tract with...."
- acs_rent_median above/below the  median of all census tracts in the city. 


In the near term, @emkap01 is planning to do a refresh of the data sources list, which will help to build on this list. We should also get input on this from Scott at CNHED. This will let us add to the list of filter criteria. But I think that the above should give us a solid starting point to build from.

**Comment by Nunie123** [comment]
@NealHumphrey I was thinking of building a table or two that would be the target of the API calls from the map filter front end.  

However, it might not be worth it if people are making changes soon to the existing tables.

Do you think it's worthwhile to proceed with what we've got, and then iterate as the tables get updated, or wait for the changes to take place and then build the tables that will be the target of our API calls?

**Comment by NealHumphrey** [comment]
@Nunie123 I can do a very quick pass this afternoon to handle a few key issues, to get you close enough that later edits won't be to egregious:
- rename all above noted column names
- Make zone names consistent for all above tables (and hopefully others)
- Eliminate the census_mapping table be instead using consistent naming during cleaning
- Add a new table called census, and put acs_median_rent data into that table, as a placeholder for when get the API method done and we'll have lots of more columns. I'll remove the current 3 current census tables, so we won't have the upper and lower quartile rent for the time being (they'll be back in once the data from the census API is working). 

How does that sound?

**Comment by Nunie123** [comment]
@NealHumphrey You're the man.

**Comment by NealHumphrey** [comment]
@Nunie123 I got this working with my most recent pull request. I'm having trouble with the live database and applying the changes - I will need to deal with that tomorrow morning (Saturday). But, if you do anything before then you can use the local docker database by pulling the latest dev branch.

**Comment by Nunie123** [comment]
Linking to @thischrisoliver 's google sheet which shows a breakdown of data points and their priority for including in the filtering.  Thanks, Chris!

**Comment by Nunie123** [comment]
I was thinking that our filter api might just give us a data dump of relevant fields every time the main page loads.  There are not that many records, so performance should be pretty quick for the download.  Then doing the actual filtering in JS will make for good responsiveness.

The below zip file contains a json and csv of what the data dump would potentially look like.  Since the project to subside tables are a one-to-many relationship, each row represents one subsidy (not one project).  We'll have to dedupe in JS, but it makes the api calls much easier.

The SQL I ran to generate these files is also below.

Would appreciate anybody's thoughts.

[derived_tables.zip](https://github.com/codefordc/housing-insights/files/982078/derived_tables.zip)

[filter_api_dump.zip](https://github.com/codefordc/housing-insights/files/982069/filter_api_dump.zip)

**Comment by NealHumphrey** [comment]
@Nunie123 to talk about with some front end people tonight: instead of de-duping the data, would it make more sense to either a) denormalize the data by adding columns for stuff like subsidies based on a max number of subsidies (i.e. columns for subsidy1, subsidy2, subsidy3), or b) to use the JSON format to nest the sub-tables of data (i.e. subsidies = [subsidy1,subsidy2])
