### ISSUE TITLE
Update Docs for Current Data Ingestion Workflow

### ISSUE THREAD

**Issue by xee5ch** [codefordc/housing-insights#255]
Per tonight's meeting will try to update data ingestion doc in onboarding resources accordingly to focus on dataset provenance, DB tables, and ingest prioritization.

**Comment by NealHumphrey** [comment]
@xee5ch I'm assuming this was covered by your PR, so I'm closing the issue - if there is something additional you needed to add, feel free to re-open the issue and comment as to what additional stuff might be needed.
