### ISSUE TITLE
DataReader - Runtime Error: cannot connect to s3 URL for data

### ISSUE THREAD

**Issue by jkwening** [codefordc/housing-insights#292]
@NealHumphrey I finished my dchousing code last night and it I was able to load into the data base without an issue until after I merged in all the new code from dev. There were some conflicts which I was able to resolve - related to what I have in my manifest.csv vs dev, my load_data refactor as a class, and additional methods I've added to MarApiConn.

When I run load_data.py docker rebuild everything works fine until it gets to my new append dchousing csv files. I get the following runtime error: `RuntimeError:   Error: Cannot connect to URL 'https://s3.amazonaws.com/housinginsights/raw/preservation_catalog/20170315/dchousing_append_project.csv'
  HTTP Response status code & reason: 404 Not Found`
Even though I passed load_from = 'file'.

The culprit is the following new code in DataReader.DataReader().__init__():
`# Test connection to s3 URL
        if self.manifest_row['include_flag'] == 'use':
            self._suppress_verbose_error_reporting()
            content_type_header = self._test_connection_to_URL(self.s3_path)
            self._restore_verbose_error_reporting()
            if content_type_header is not None:
                logging.info("  Content (MIME) type: {}".format(content_type_header))`

If I understand correctly what this connection validation is doing, then I think it needs to be nested within the following code a few lines further down:
`# Load data file from given file system - S3 or local
        if load_from == "s3":
            self.path = self.s3_path
            self.path_type = "url"`

Else any data that someone tries to load locally for testing will fail if isn't already in the s3 bucket - that is, if my understanding of all the new changes is correct. 

The suggested change resolved the issue on my end so once this is clarified I can complete my pull request for #194 and this fix will be included.

**Comment by NealHumphrey** [comment]
@jkwening Interesting. @dogtoothdigital does John's suggested change match with what you were intending for that updated code? As john alludes to, we do want the ability for users to load data that is only stored locally and is not yet uploaded to S3. 

@jkwening I can test this myself later and look at the actual code to provide a better insight, can't do it tonight

**Comment by dogtoothdigital** [comment]
Yes, @jkwening, this makes sense.  It was not my intention for the error-checking in DataReader to create a nuisance; my apologies. Also, sorry for the delay in getting back to you.

cheers, 
-meg

**Comment by jkwening** [comment]
Cleaning up related data ingestion issues - closing because it looks like this has been completed.
