### ISSUE TITLE
Add crow distance to wmata_dist table

### ISSUE THREAD

**Issue by NealHumphrey** [codefordc/housing-insights#312]
To speed up processing of rail distances, I pulled in the haversine calculation of crow distances based on lat/lon pairs. Since we have this calculation available, we might as well add it to the database. 

Currently the calculation is only in the _find_rail_stations method. 
- Add calculation to the _find_bus_stations method
- Add it to the distOutput as a new key value pair ('crow_dist': 0.5)
- Add new column to meta.json
- Run the process from start to finish (download data, update manifest, add to database) to make sure it all works. 

Not urgent, plan for v2

**Comment by jkwening** [comment]
Cleaning up related data ingestion issues - closing because it looks like this has been completed.
