### ISSUE TITLE
Cache walking distance calculations

### ISSUE THREAD

**Issue by NealHumphrey** [codefordc/housing-insights#313]
The walking distance calculation is very time consuming (4+ hours) due to the rate limit imposed by Mapbox. In reality we only need to run this once per pair of locations (building+station). Stations and buildings rarely move (mostly in cases of data errors not actually due to moving). However, if the lat/lon of a building or station changes (though the ID of that station did not change) we do want to rerun the calculation. 

Here's a proposed quick solution that has minimal impact on the rest of our workflow as it doesn't require us to do tricky state management of changing lat/lons for specific ids. 

- Add the 4 numbers for start and end lat/lon to the wmata_dist table, to cache the specific lat/lon values that were pulled from the project and wmata_info tables when the distance was calculated. 
- Add an optional argument to WmataApiConn.__init__ for 'use_cached_distance' and set it to True by default. if self.use_cached_distance is true, we don't need to get the walking distance if we already have it. if False, we'll behave as normal and get fresh walking calculations for all points. 
- Edit the `self._get_walking_distance` method to first query the database for a row corresponding to that exact set of 4 lat/lon values. If the wmata_dist table does not exist (i.e. we are building it the first time or want fresh data) or if there is no matching row (either because it's a new building or because one of the lat/lon values has been changed) proceed with getting the walking distance from the API.

**Comment by NealHumphrey** [comment]
@jgordo04 If you're not too sick of working on distance calculations - this and #312 are two enhancements so that our server won't have to run the wmata_dist code for 5 hours every week!

**Comment by jgordo04** [comment]
No prob. Happy to!

**Comment by jkwening** [comment]
Cleaning up related data ingestion issues - closing because it looks like this has been completed.
