### ISSUE TITLE
Home Stretch - Final Items for June 13

### ISSUE THREAD

**Issue by NealHumphrey** [codefordc/housing-insights#316]
For discussion and editing in our session tonight - my first pass at what I see remaining. TBD how many of these we can complete. 

Data ingestion:
- [x] @jkwening Add meta.json back into the API
- [x] @jkwening Automatic update of the manifest.csv when the get_api_data is run
- [x] @louvis (and/or @HLKwon @ncclementi) Ensure consistent column name and data structures for all current tables
-  [x] @MikeS-nth  Add ~15-20 census data fields
-  [x] @ajhalani Add weighting factors for census data?
- [x] @emkap01 (+others) Data documentation pages for all data sources we actively have (including JS to pull in field descriptions from the meta.json from the API)

API
- Add endpoint for census data that applies weighting factors?
- Add endpoint for Filter categories / configuration? Or build it on the front end
- Verify that for chloropleth/browse data sources that we know which aggregation methods we can use (i.e. neighborhood_cluster, zip, etc.) - with consistent column name / data structure implemented our existing endpoint should work. 

(edit: moved all front end items to #317)

**Comment by emkap01** [comment]
Data documentation for all raw datasets used in the production db is being worked on, the status of each one is being tracked via [this sheet](https://docs.google.com/spreadsheets/d/1EcjViJq2SuiHEEiRu9TemVJ29oNrNV7ibC6NofJiXzA/edit?usp=sharing).
