### ISSUE TITLE
Quick fixes this week for V1

### ISSUE THREAD

**Issue by NealHumphrey** [codefordc/housing-insights#344]
Pulling the top priority items out of [this google doc](https://docs.google.com/document/d/1R5nEh86T5yj1W4N3eqgiHHzZx9-QgTG4UxL8c76s2-k/edit)

- [x] Shrink circle size at moderate zoom level to avoid overlap
- [x] Add pillboxes for each filter that's selected along the top of map, as in mockup (this method provides better feedback as to what is currently filtered when you switch over to the layer view)
- [ ] Add a 'more info' link to each data explanation linking to the appropriate  table in our docs (probably want to do it via an additional configuration key in the initialOverlays variable of map view, and edit the overlayMenuOption function to append the appropriate link)
- [x] Move building dots to be on top of the blue layer so that coloring is not so washed out (note, there may be a few lingering logic places that rely on layer order, so there might be some logic fixes needed)
- [x] Move location of zoom + / - control so that it is not hidden by filter/layer panel. Bonus if it can move dynamically on filter open/close
- [ ] ~~Only animate entering/exiting buildings~~ (made new issue for this, not simple to implement)
- [x] reduce the size of dot swell animation since we now also want people to notice the animating pie chart. 
- [x] Back button more prominent in Building view. 
- [x] Rename “Buildings (#)” to “Results: # Buildings” 
- [x] Header of Buildings tab that describing donut charts:  “Your filters match 121 out of 545 buildings. This is: " and change "Buildings" to "of all buildings" and Units to "of all units"
- [x] Fix ACS median rent filter. Currently every item in the filterData collection has an 'acs_median_rent' of 'null'. As of 17 June, the acs_rent_median API endpoint doesn't seem to be working ([see](http://hiapidemo.us-east-1.elasticbeanstalk.com/api/raw/acs_rent_median)). 
- [x] Add more data sources to layers

API:
- [x] Update the census endpoint to apply weighting factors to create Ward and Neighborhood Cluster data correctly
- [x] Add 5 remaining calculated factors to census endpoint

**Comment by NealHumphrey** [comment]
I've got most of the pillboxes (item 2) working - got them showing up / disappearing, just need to style slightly and add the callback function

**Comment by ptgott** [comment]
@NealHumphrey I've updated the line item related to acs_rent_median. This seems to be a back-end issue, as all of the values received from the filterData endpoint are 'null'.

**Comment by ptgott** [comment]
@NealHumphrey I'll be working on some of the quick fixes in #355.

So far, I've just commented out the acs_median_rent filter, making a note that I've done so because of the issue with all the values being 'null'.

**Comment by NealHumphrey** [comment]
Another thing I noticed in playing with the site - with the new added layer
data sources, the zone selection are no longer obvious, especially on small
screens. Maybe we should make these sticky to the bottom of that side panel
and only have the scrolling for the data sources section

On Jun 17, 2017 12:35 PM, "Paul Gottschling" <notifications@github.com>
wrote:

@NealHumphrey <https://github.com/nealhumphrey> I'll be working on some of
the quick fixes in #355
<https://github.com/codefordc/housing-insights/pull/355>.

So far, I've just commented out the acs_median_rent filter, making a note
that I've done so because of the issue with all the values being 'null'.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/codefordc/housing-insights/issues/344#issuecomment-309232330>,
or mute the thread

**Comment by emkap01** [comment]
FYI I noticed that "ANC" is missing from the filter shelf.  I couldn't find anything in the Issues to indicate whether that was something we specifically opted to hold back for a future version, or whether it's just an oversight.

**Comment by NealHumphrey** [comment]
@emkap01 - 'ANC' is currently listed in the filter shelf. Not sure if it was missing at some point, but there now. Note, it's not available as a layers option though.

**Comment by NealHumphrey** [comment]
Closing this issue - opened two separate issues for the last remaining components, everything else is done!
