### ISSUE TITLE
Only animate entering/exiting buildings

### ISSUE THREAD

**Issue by NealHumphrey** [codefordc/housing-insights#350]
For consideration in the map view - not 100% certain this is worth the added overhead, but would help especially with the exiting dots that right now just disappear. 

I looked into doing this as part of #344 but decided it wouldn't be a quick fix. @ostermanj can advise on best approach, but here's my best guess as to how to implement it by adapting the current approach:

- in `mapView.placeProjects`, instead of adding 1 copy of 'convertedProjects' instead add 3 copies - an 'entering' 'staying' and 'exiting' copy. 
- Similar to how the 'matches_filters' code works at the top of the callback, set an 'show_in_view' state to 'true' or 'false'. Probably want to keep the 'matches_filters' property too, for potential use with other logic.
- On initial load, set all the buildings to be 'true' only for the 'entering' copy and false in the other two. 
- In the `mapView.filterMap` method, in the same area as we currently set the 'matches_filters' property, reassign the properties to where they each need to be - if currently in 'entering' and in the filtered list, set 'staying' to true and the other two to false. If currently in 'staying' and not in the filtered list, set the 'exiting' copy to true and the other two to false. Etc. 
- in animateSize, perform both sets of animations - entering and exiting.

**Comment by ostermanj** [comment]
I may be able to jump on this before the June 20 meeting. It may be hard to target specific circles within a single mapBox layer; if so the the *staying*, *entering*, and *exiting* categories may need to be separate layers. Will see . . .

**Comment by NealHumphrey** [comment]
@ostermanj  I agree that it doesn't look easy/possible to target specific circles in a mapbox layer, at least with how the animations are currently configured. I was envisioning those being 3 separate layers, managed in a way that all buildings exist in all layers but are turned on or off so that they are only shown in 1 (or none) of the layers.

**Comment by ostermanj** [comment]
Yeah, I'm working on it now. mapBox native transitions and data-driven-styling looked promising but the two don't really work with each other. Transitions seem to only work when the value is changed from one number (as type) to another number. So I'm going the multiple layer route. Should work . . .

**Comment by ostermanj** [comment]
There may be some timing issues cross-browser about when to fire the animations (in setTimeouts), but by and large this is done. I'll close the issue; if the timings prove difficult we can open a new issue. If so, it may be better to go back to the requestAnimationFrame method.
