### ISSUE TITLE
dchousing buildings not filtering properly due to missing attributes

### ISSUE THREAD

**Issue by NealHumphrey** [codefordc/housing-insights#353]
Need to geocode the dchousing buildings with the relevant fields - convert ward to not be all upper case (use "Ward 1" instead of WARD 1), and add in data for census_tract, anc, zip, neighborhood_cluster, neighborhood_cluster_desc, etc. 

Currently some buildings that show up as being in a given ward are dissappearing from the view when a ward filter is selected. @txomashernandez heads up in case any user testers notice it, just a small data quality issue.

**Comment by jkwening** [comment]
@NealHumphrey yeah I noticed this yesterday as I was adding cleaner code to fix the geocode issue from ticket #314. I plan on fixing this along with that ticket, hence why I haven't submitted PR yet.

**Comment by NealHumphrey** [comment]
Oh! Sorry about that, these are essentially the same issue, I forgot I
created that other one.

On Jun 17, 2017 1:54 AM, "John Kwening" <notifications@github.com> wrote:

@NealHumphrey <https://github.com/nealhumphrey> yeah I noticed this
yesterday as I was adding cleaner code to fix the geocode issue from ticket
#314 <https://github.com/codefordc/housing-insights/issues/314>. I plan on
fixing this along with that ticket, hence why I haven't submitted PR yet.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/codefordc/housing-insights/issues/353#issuecomment-309192625>,
or mute the thread

**Comment by jkwening** [comment]
Closing - resolved with PR #371
