### ISSUE TITLE
Zone buttons always visible

### ISSUE THREAD

**Issue by NealHumphrey** [codefordc/housing-insights#359]
With more layer data sources now available, making the list of data sources longer, the zone selection buttons are no longer obvious, especially on small screens. 

Suggest making these sticky to the bottom of the left hand 'layers' side panel and only have the scrolling for the data sources section above it.

**Comment by NealHumphrey** [comment]
@ostermanj If you have a few minutes to give this a shot, it should be a relatively simple CSS fix and I anticipate there will be some usability confusion for folks on this.

**Comment by ostermanj** [comment]
All set in PR #362

**Comment by ostermanj** [comment]
Closing issue. Resolved.
