### ISSUE TITLE
Show/hide bottom legend

### ISSUE THREAD

**Issue by NealHumphrey** [codefordc/housing-insights#364]
Ward 8 is always hidden by the building legend when on a laptop sized screen. In desktop it collapses down to one level. 

Add a show/hide button to transform from a minimized state to a full state. Minimized version should look like this mockup, but with only the 'building layer' bar since we already put the "Contextual layer" into the sidebar itself. 
https://app.moqups.com/neal@nhumphrey.com/dDYbZTfu6T/view/page/a470464c5

**Comment by ostermanj** [comment]
May be unnecessary if we merge in changes from #376
