### ISSUE TITLE
Street view and image url for non-PresCat projects

### ISSUE THREAD

**Issue by NealHumphrey** [codefordc/housing-insights#373]
PR #371 adds the ability to get properly geocoded fields from the MAR for projects that are missing them. We should also add the ability to get street view and proj_image_url from the MAR, plus any other fields that are available in the mar and null in our existing data. 

See this example URL to cross reference what is available from the MAR with the nulls we have in the current project table: http://citizenatlas.dc.gov/newwebservices/locationverifier.asmx/findAID2?f=json&aid=233807

**Comment by jkwening** [comment]
@NealHumphrey Thanks for the info. I was unsure whether to populate nulls for this field or not but it seems for completeness I should see if I can encode all data fields for PresCat project table if possible and readily available. I'll work through all fields again and see what else can be cleaned up.

**Comment by jkwening** [comment]
Closing this ticket because it's being resolved in this ticket #379
