### ISSUE TITLE
Switch dchousing to pull csv directly

### ISSUE THREAD

**Issue by NealHumphrey** [codefordc/housing-insights#374]
From #194: 
Flagging a future issue we'll run into using the endpoint you set up for dchousing. ESRI by default limits the API calls to 1,000 records, as we found in #198 . Using the geojson endpoint but swapping .geojson for .csv will return the full api data already formatted as .csv. 

Change the data download method for the DCHousing.py - instead of using geojson and converting, download as a CSV file directly, the way is done in opendata.py. **OR**, simply add dchousing data source to the opendata.py class and adjust meta.json to match.

**Comment by NealHumphrey** [comment]
Note, this will only be an issue if the dchousing data set reaches greater than 1,000 records; the current code works as-is. This will help us future-proof the data collection process.

**Comment by jkwening** [comment]
Completed and merged in PR #378 - closing ticket
