### ISSUE TITLE
Download CSV functionality

### ISSUE THREAD

**Issue by NealHumphrey** [codefordc/housing-insights#389]
Add a download button to the 'matching projects' tab of the map view. This should export a CSV file with the projects that match the current filters (with all the columns associated with them). To start, this will only contain the fields in the project table. After completion of #388, this can also include zone data. In addition, it should export a text file with the list of the currently applied filters. 

MVP:
- [ ] Create an API endpoint that provides the project table in CSV format (Python)
- [x] Client side, when the download button is pressed, get this full project table in CSV format. Add a column called "matches_filters" as the first column and populate it with true/false based on whether the nlihc_id is found in the current FilteredData list. (FrontEnd)
- [x] Allow the user to download the file to their local computer. (FrontEnd)

Improvements:
- [ ] After #387 is complete, use the urlState object generated as part of that process to create a user-readable text representation of the filters that have been applied in that view. 
- [ ] After #388 is complete, in the csv endpoint, join the project table to the ZoneFacts table to add columns for the denormalized data about the neighborhood facts. 

Alternatives:
Another approach to creating the CSV is to do a 'GET' request to the csv API endpoint that passes the list of matching nlihc_ids to the API and adds the true/false on the server. Explore this if it is difficult to edit the csv data and then download on the client side.

**Comment by jgordo04** [comment]
@NealHumphrey This ticket is on it's way, but I have a few questions. 
1. Do you want JUST the filtered projects exported or all of them + the added matches_filter column? 
2. The way I have it now, I didn't write a python API, I just grabbed what was stored in allData.filtered and output that. BUT I found the fields are not identical. The database has:
- klass
- mar_id
- xcoord
- ycoord
And the stored data on the site does NOT have those, but does have:
- proj_x
- proj_y
Does proj_x == xcoord and proj_y == ycoord? and what are klass and mar_id? Is it a problem that they aren't there? If so, I can query the db, but this was a very quick solution. 
3. I'm assuming you just want the button to export 2 files based on the initial paragraph? One with the list and one with just a list of the filters?

**Comment by NealHumphrey** [comment]
Jamie,

Let's export all projects with extra column, ideally sorted so that
matching projects come first?

Klass is the column that corresponds to whether it matches the current
filters, so that is an expected difference.

I am not sure about the other column differences, but make a pull request
and I'll look into it. Might just be a slight mismatch in which version of
the database you are looking at and which one is used for API because the
dev branch now draws from the new code for DC server as of a couple days
ago.

And yep 2 files. There is no way to do a tab or header section in a plain
csv so figured that was best way to preserve choices


On Aug 1, 2017 9:09 PM, "Jamie" <notifications@github.com> wrote:

@NealHumphrey <https://github.com/nealhumphrey> This ticket is on it's way,
but I have a few questions.

   1. Do you want JUST the filtered projects exported or all of them + the
   added matches_filter column?
   2. The way I have it now, I didn't write a python API, I just grabbed
   what was stored in allData.filtered and output that. BUT I found the fields
   are not identical. The database has:


   - klass
   - mar_id
   - xcoord
   - ycoord
   And the stored data on the site does NOT have those, but does have:
   - proj_x
   - proj_y
   Does proj_x == xcoord and proj_y == ycoord? and what are klass and
   mar_id? Is it a problem that they aren't there? If so, I can query the db,
   but this was a very quick solution.


   1. I'm assuming you just want the button to export 2 files based on the
   initial paragraph? One with the list and one with just a list of the
   filters?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/codefordc/housing-insights/issues/389#issuecomment-319539579>,
or mute the thread

**Comment by jgordo04** [comment]
Created a pull request. Right now it only exports a csv. Where are the filters it's using stored? I couldn't find it. We can take this offline on Slack ( @NealHumphrey ) .

**Comment by NealHumphrey** [comment]
Completed!
