### ISSUE TITLE
Refactor API to access housinginsights package

### ISSUE THREAD

**Issue by NealHumphrey** [codefordc/housing-insights#400]
MVP:
- [x] Move the application.py file up one level (into the python folder)
- [x] write an example function/endpoint in application.py that needs something within the housinginsights package (this could be a simple 'helloworld' function created inside the package). 
- [x] Deploy to the server and make sure that it can run. 

Continued development:
- [x] @jasonrhaas refactor the declarative app into a blueprint and register it on the app
- [x] (@nealhumphrey) Refactor current code into file structure and make sure existing endpoints work. Move all the existing endpoints out of application.py and into a blueprint. I think we start with just putting them into a single 'old_endpoints' blueprint and then as we decide which new endpoints that will be added as the design for the Project Page (#399) gets finished we'll have a better idea of how to structure them. 
- [x] (@nealhumphrey) Propose a file structure so that the current content of application.py can be put into logically separate places. Partially discussed in #249 
    - api folder can have multiple files related to API endpoints: grouped by the type of data they provide? break off 'utils' into a separate file? 
    - cron jobs
    - email-sending functionality

**Comment by jasonrhaas** [comment]
I should have the ORM models done today with a basic GET API on top of it, including pagination.  The models are very clean and should be easy to maintain.  The main this that needs to be added is primary keys for a bunch of the tables.  SQLAlchemy and ORM only works well if you have solid primary keys.  For the tables that don't have unique values for this stuff, SQLAlchemy can auto generate it.

Classes look like this:

```
class Census(Base):
    __tablename__ = 'census'

    census_tract_desc = Column('census_tract_desc', Text)
    census_tract = Column('census_tract', Text, primary_key=True)
    total_population = Column('total_population', Integer)
    acs_lower_rent_quartile = Column('acs_lower_rent_quartile', Integer)
    acs_median_rent = Column('acs_median_rent', Integer)
    acs_upper_rent_quartile = Column('acs_upper_rent_quartile', Integer)
    state = Column('state', Text)
    county = Column('county', Text)
    tract = Column('tract', Text)
    unique_data_id = Column('unique_data_id', Text)
```

The returned JSON from the endpoint `localhost:5001/api/census` looks like this:

```
{
  "num_results": 1255, 
  "objects": [
    {
      "acs_lower_rent_quartile": null, 
      "acs_median_rent": null, 
      "acs_upper_rent_quartile": null, 
      "census_tract": "11001000201", 
      "census_tract_desc": "Census Tract 2.01, District of Columbia, District of Columbia", 
      "county": "001", 
      "state": "11", 
      "total_population": 3844, 
      "tract": "000201", 
      "unique_data_id": "acs5_2014"
    }, 
    {
      "acs_lower_rent_quartile": 1697, 
      "acs_median_rent": 2001, 
      "acs_upper_rent_quartile": 2001, 
      "census_tract": "11001000202", 
      "census_tract_desc": "Census Tract 2.02, District of Columbia, District of Columbia", 
      "county": "001", 
      "state": "11", 
      "total_population": 4080, 
      "tract": "000202", 
      "unique_data_id": "acs5_2009"
    }
  ], 
  "page": 1, 
  "total_pages": 126
}
```

**Comment by jasonrhaas** [comment]
Check out Pull Request #410.  I have the base Flask RESTLESS endpoints up and running using the ORM approach.

**Comment by jkwening** [comment]
@NealHumphrey Surprisingly, after reviewing Jason's PR request last night I actually think I understand what he implemented so I can take a crack at this if you can't get to it today.

**Comment by NealHumphrey** [comment]
@jkwening I'm taking a look at his PR right now; I'm going to take a crack at at least doing the hoisting up a level and testing that it is deployable to AWS. After that is done, we can open up cron jobs #402 while simultaneously doing the migration to combine this RESTLESS approach w/ our current endpoints. I have a few family things midday so will keep you updated on where things stand and what I get done so we don't cross paths.

**Comment by NealHumphrey** [comment]
@jasonrhaas - see my updated description of this issue at the top of this page. I moved the checklist from #412 into here (it was mostly duplicated) - most notably, immediate next step is to refactor the declarative app into a blueprint, and to move all of the existing endpoints into another blueprint.

**Comment by NealHumphrey** [comment]
Refactoring continues in #429

**Comment by NealHumphrey** [comment]
Completed!
