### ISSUE TITLE
Scheduled CRON jobs on server for data collection

### ISSUE THREAD

**Issue by NealHumphrey** [codefordc/housing-insights#402]
We want our data ingestion and processing to occur automatically, on a regular schedule
- Check for new data weekly, or on a data set-specific schedule, or on demand when requested by admin
- Download and ingest all new data (will require refactoring to make it work in server environment)
- Handle all data ingestion problems via logging and skipping (many things currently can crash the code if something goes wrong)
- Alert admins via email of the data collection status - any missing/skipped data sets, any data ingestion problems.

**Comment by speedyturkey** [comment]
I'd like to start working on this ticket if I can. I have a couple of questions which I'll post to Slack.

**Comment by speedyturkey** [comment]
Putting this back for the time being, seems like it isn't as ripe as some other tickets.

**Comment by speedyturkey** [comment]
I'd like to start taking a look at this. After discussion with @jkwening , it sounds like we'd benefit from some centralized logging functionality, which I have some ideas on.

Ultimately, it seems that the scheduled job (however it is scheduled) will need to call the code in get_api_data.py.

**Comment by NealHumphrey** [comment]
@speedyturkey awesome, yes! Go for it. When we finalize the #400 issue we can get the scheduling code into the right place, but until then setting it up to be able to call get_api_data and do proper logging would be a big start. We especailly will want any warning-level logging to be sent on to the admin so we'll want to separate out regular from warning (or higher) logging in some way

**Comment by NealHumphrey** [comment]
Closing in favor of more recent #470 that has more details and overlaps w/ this
