### ISSUE TITLE
Add nlihc_id to topa table

### ISSUE THREAD

**Issue by NealHumphrey** [codefordc/housing-insights#404]
The TOPA notices table will sometimes correspond to records in our projects table - though there will be many additional TOPA notices for addresses that are not part of the projects we know about. To be able to join these two tables, we want to add the `nlihc_id` (which is the unique identifier for the project table) . Check the cleaning of the 'dchousing' data set for an example of how to do this.

**Comment by NealHumphrey** [comment]
- Project table has a field mar_id which should match to the address_id from the topa table. 
- Any non-matching records can have null nlihc_id

**Comment by speedyturkey** [comment]
Grabbing this one. Spoke to Neal and John and it will hopefully be an easy one (fingers crossed).

**Comment by speedyturkey** [comment]
In speaking with @jkwening about this, it looks like the Cleaners do not currently have access to the database connection. My current plan is to have load_data pass the db engine to the base cleaner so that I can do the lookup on ID. That way, anyone who needs to do similar lookups at this stage in the future will be able to. Please let me know if this conflicts with your understanding of things.

**Comment by speedyturkey** [comment]
An alternative implementation would be to perform this update all at once as a post-processing script. If we add nlihc_id to topa table we can do:

```sql
update t
set
  nlihc_id = p.nlihc_id
from topa as t
inner join project as p
  on t.address_id = cast(p.mar_id as numeric)
```

**Comment by NealHumphrey** [comment]
@speedyturkey I'd probably vote for option 1, adding database access to Cleaners.py - that way we're consistent with the one place that we modify data.

**Comment by speedyturkey** [comment]
Thanks for that guidance Neal. I made a WIP PR #415 with some further comments. In short, I have added some necessary functionality but could use some direction on how to complete the issue.

**Comment by NealHumphrey** [comment]
Completed
