### ISSUE TITLE
Add 'Subsidy Expiration Date' filter to map view

### ISSUE THREAD

**Issue by emkap01** [codefordc/housing-insights#418]
Per Issue #401, users will need the ability to filter the map view based on the expiration date of the subsidy/subsidies covering each project.

Since the subsidy table in the Postgres db already includes the subsidy expiration date value in the field labeled `poa_end`, and since each project is already represented in the subsidy table as well via the `nlihc_id` field, the subsidy table already has all the necessary data for the filter in it.

The details required for the filter also exist already in /docs/tool/js/views/dataChoices.js, although the `min` and `max` fields need to be changed to valid formats:

```
        {   "source":"poa_end",
            "display_name":"Subsidy End Date",
            "display_text": "Filters to buildings with at least one subsidy whose end date falls between the selected dates.",
            "component_type": "date",
            "data_type": "timestamp",
            "min": "1950-01-01", //just example, TODO change to date format
            "max": "now",         //dummy example
            "data_level": "project"
        },
```
Additionally, per discussions with the front-end team, we also still need to modify /docs/tool/js/views/filter-view.js.  Specifically, the following code needs to be modified in order to handle dates:

```
            if (filterView.components[i].component_type == 'date'){
                //Add a div with label and select element
                //Bind user changes to a setState function
            };
```
The last step will be to add the field to the filter_data api endpoint.

**Comment by louvis** [comment]
See below for sample SQL to pull subsidy expiration dates. This example only pulls projects with subsidy expiration dates past the current date. It also restricts those results to the subsidies with earliest end date.

'SELECT nlihc_id
	, MIN(poa_end) AS first_end
FROM
	(SELECT nlihc_id
		, poa_end
	FROM 
		(SELECT nlihc_id
			, poa_end
			, poa_end>=CURRENT_DATE AS date_answer
		FROM subsidy) AS date_test
	WHERE date_answer='t') AS future_end_dates
GROUP BY nlihc_id'

**Comment by NealHumphrey** [comment]
Completed
