### ISSUE TITLE
API endpoint for project + zonefacts

### ISSUE THREAD

**Issue by NealHumphrey** [codefordc/housing-insights#432]
Create a project table endpoint that joins the `project` table to the  `ZoneFacts` table 3 times, once for each zone type (ward, neighborhood_cluster, census_tract). This join should be used for to replace the current 'project' endpoint in the front end app (stored in /core/housing-insights.js URLS: project), to provide additional columns of data to anywhere the project table is used.

**Comment by jkwening** [comment]
@NealHumphrey is this the same task as the last action item in #388 - left join project table/zone_facts?

**Comment by NealHumphrey** [comment]
@jkwening Yep! And it's actually what I just put into the PR in #438 (sorry should have updated these ticket too!)

**Comment by NealHumphrey** [comment]
Resolved in #438
