### ISSUE TITLE
Filter UI not reset properly in some circumstances

### ISSUE THREAD

**Issue by NealHumphrey** [codefordc/housing-insights#442]
- [x] Resetting values to original levels doesn't clear the filter pillbox. 
    - This works: uncheck 'unknown values' checkbox => pillbox added; recheck unknown values => pillbox removed
    - Doesn't work properly: 
        a) Slide value away from min or max; 
        b) slider value back to maximum/minimum
        Actual: pillbox not removed, filter values are simply set to their min/max. 
        Expected behavior: resetting the slider to a level matching its original level will set that filter as 'cleared'. 

- [x] Pressing 'x' in the pillbox toggles the 'unknown values' checkbox to the wrong state in some circumstances. This occurs if both the checkbox and the slider have been used. This is caused by the first problem in combination with some incorrect logic about checkbox state. 
    - Doesn't work properly:  For one of the slider data sets (e.g. Total units), 
        1) slide filter to some value 
        2) uncheck the checkbox 
        3) re-check the checkbox
        4) click the 'x' in the pillbox. 
        Actual: Checkbox is switched to unchecked when the filter is cleared. This does not accurately reflect the state of the filters, which in reality do include nulls. Clicking the checkbox again once does nothing, and clicking a final time restores the sync of state to ui. 
        Expected: Checkbox remains unchanged when clearing filter because it is already checked.

**Comment by NealHumphrey** [comment]
#451 resolves the second issue. First issue still outstanding.

**Comment by ostermanj** [comment]
First issue is addressed in PR #458
