### ISSUE TITLE
Extend url encoding/decoding to handle decimal values

### ISSUE THREAD

**Issue by NealHumphrey** [codefordc/housing-insights#467]
Any of the dataChoices that are formatted as a 'percent' (e. g. poverty rate) have a value of less than 1. URL encoding currently rounds this to 1 or zero. Should instead allow these to have 2 decimals of resolution, i.e. 0.03 or 0.54.

One option: To keep url short, could format anything that is a percent data field as multipled by 100? Then the url will be x=23-56 for the field x with values of 0.23 and 0.56.

**Comment by ostermanj** [comment]
Addressed in PR #478. Any needed rounding is happening upstream in the filter controls, so just removing the extra rounding in router.js seems to do it.

**Comment by NealHumphrey** [comment]
@ostermanj This works on the encode portion, but decoding does not seem to work. If I set a filter (e.g. poverty rate) the url changes. If I then refresh the page to reload it with the url that now has poverty rate encoded in it, instead of applying the filter the url decoder erases the rate data from the url and loads the page without that filter applied. If there are other filters encoded in the url, those filters are not affected and are appropriately applied. 

I will not prevent this from merging #478 since the first part is working and is an improvement to current status, but I will keep this issue open so we can resolve this in a future PR.

**Comment by ostermanj** [comment]
Ok -- I'll check on it. Thought it was working . . .

**Comment by ostermanj** [comment]
The decimal filter is working for me on Chrome, FF, and Safari (Mac). I wonder if it's a cross-browser / platform or edge-case issue. @NealHumphrey can you still reproduce the error?

**Comment by NealHumphrey** [comment]
@ostermanj I couldn't recreate. Assuming it is fixed now so closing ticket
