### ISSUE TITLE
Communicating null values to users

### ISSUE THREAD

**Issue by NealHumphrey** [codefordc/housing-insights#469]
Even with the addition of our 'Include projects with null values?' checkbox, the impact of nulls are not totally clear to users. This was most apparent in Scott's user test related to subsidy end dates. 

Ideas:
- At a minimum, use a tooltip near the checkbox to explain null values to users and why they would exist
- Beside the null value checkbox, provide a count of the number of projects with null values that occur in that field as an indicator that the user should pay attention to this. 
- In the Summary column include a warning that reports how many of the existing projects have null values for at least one of the active filters? This could be a [dismissable alert](https://www.w3schools.com/bootstrap/bootstrap_alerts.asp) - making it a dismissable alert will make it more obvious to users, but after it is dismissed it might not do its job if they later filter to something that has nulls again. We probably don't want it to keep popping up every time. It could also be a permanent feature, but it might end up looking less obvious - maybe color code it red if there are any filters that have nulls, gray if none?
- Untoggle 'include projects with null data' the first time a filter is set. We want checked to be the default when a filter is not selected (so that filter will not be applied), but 'excluded' is probably a better default for when users apply a particular filter. We'll need to be careful of when this occurs so that we only uncheck the toggle the first time, not every time they use the slider - if they manually toggle it back on we don't want to untoggle it every time. 

Any other ideas / alternatives? What do people think is the most effective way to improve this for users?

Suggested by @emkap01 : change text of checkbox helper to be "include projects with missing `<dataname>`?" i.e. "include projects with missing subsidy start date?"

**Comment by jamiecatania** [comment]
Working on the following fixes, as noted above:

1. (Dev In Progress) Use a tooltip near the checkbox to explain null values to users and why they would exist
2. (Not Yet Started) Provide count of projects with null values next to checkbox.
3. (Not Yet Started) Provide warning in Summary column with count of projects with null values for at least one of the active filters.
4. (Not Yet Started) Untoggle checkbox the first time a filter is set.
5. (Merged) Change text of checkbox helper to be "include projects with missing <dataname>?"

**Comment by NealHumphrey** [comment]
Great! @jamiecatania I'd say that of the remaining ones 4) is the highest priority. 

2) would be a good bonus if you have time, though we may have you switch to project view by that point. 

I think that 3) is probably not necessary. If the others are done users will only end up with nulls if they actively choose to, which makes 3 less relevant.

**Comment by NealHumphrey** [comment]
1. in progress of course is useful too and not too complicated so do finish that one.

**Comment by jamiecatania** [comment]
Sounds good @NealHumphrey - 1 & 4 are the priority for me tonight then.

**Comment by jamiecatania** [comment]
Opened a PR with a few questions here: https://github.com/codefordc/housing-insights/pull/520

**Comment by NealHumphrey** [comment]
Completed
