### ISSUE TITLE
Prototype #1: Moving Blocks

### ISSUE THREAD

**Issue by NealHumphrey** [codefordc/housing-insights#48]
We'll focus our first prototype on the riskiest option for our homepage - grouping buildings by category with our animated block view. To complete the experience, we'll also have examples of our individual building page and a Ward-specific page. 

**Storyboard:**
[design-1.rotated.pdf](https://github.com/codefordc/housing-insights/files/682910/design-1.rotated.pdf)

**Mockup tool:**
https://moqups.com/ (check your email for an invite to the project) 

**Roles (can be partially overlapping)**
* Box Page Lead: In charge of the main homepage view
* Building Page Lead: In charge of assembling the building view
* Component Maker: Makes custom graphs, icons, and components for the page leads to use in their views. Likely someone with moderate graphic design experience. 
* Icon/Asset downloader: Hunts down stock photos and icons in coordination with the component maker.
* Data Checker: Looks up relevant data from our data sources to make sure that components look realistic - e.g. number of buildings in a Ward, min/max market rent in the city, etc.  
* Stitcher: Coordinates connecting all the views into one seamless experience for the user

Interested in reading about the process? Here's the chapter from the book Sprint, which I've used as a guide for our entire design process. 
[Sprint-prototype-chapter.pdf](https://github.com/codefordc/housing-insights/files/676148/Sprint-prototype-chapter-rotated.pdf)

Conventions:
* Use gray to indicate elements that will be clickable/selectable in the final design but that are not included in the mockup (e.g. we may only mock up 2 out of 10 or so filtering options)
* Replace hover options with click - we will direct test users to these places during demos
* The goal of the mockup is to feel real - no Lorum Ipsum, real looking data, clean alignment of objects.

**Comment by NealHumphrey** [comment]
Realistic rent data background info:
We have two sources, which have very different methodologies and therefore values. 
* Zillow is based on listings in the market, so is more reflective of unsubsidized market rent, but doesn't normalize for home size and includes single family buildings. Bedroom and square foot normalized values are only available for a few neighborhoods (not enough data)
* The American Community Survey has 5-year averages of what people actually pay for rent, so those are driven down by including subsidized units. 

Zillow ranges from $1,273 to $6,553 as the total min max across 2010 and 2016 estimates across all neighborhoods in DC
ACS ranges from $254 to "$2000+" (exact amount over $2,000 is suppressed) across their 2009 and 2015 5-year estimates. 

Let me know what neighborhood you want and I can get you more specific numbers; figuring out how to interpret these rent data is another task for the#datateam


Thomas' question via email:
I'm working on getting Joanne and Julia some close-to-real numbers for the first mockup. I'll start with the Preservation Catalog for much of it. Julia requested some info on market rent and rent costs for individual buildings that I didn't immediately see in the catalog. For now, assuming I could find market rents on something like Zillow, but is there a data source that we will eventually be using for unit costs and/or market rent?

**Comment by txomashernandez** [comment]
Thanks, Neal! So far we have a Ward level from our mockup instead of
the neighborhood. We have Ward 5 at the moment, so if possible to get the
5-year rent data for that Ward that would be helpful. I also just mentioned
in an email that Joanne is working on the property view for Friendship
Terrace so we would ideally have the 5-year data for that property.

Thanks!
Thomas

**Comment by NealHumphrey** [comment]
The source data for rent that we are starting with is from the American Community Survey, so for now I'm providing that "as-is", which is for the Census Tract. 

Here is the full list of data for Friendship Terrace, copied from Thomas's email plus the additional fields I dug up (putting here to make available to everyone):

Friendship Terrace - 4201 Butterworth Place NW, Washington DC. 
[BuildingDetailedReport - pdf](https://github.com/codefordc/housing-insights/files/694226/NL000120-detailed.1.pdf)


Building info:
- type of ownership (profit vs non profit) Nonprofit 
- management name + contact info Episcopal Church Home, Friendship, Inc. - 4201 Butterworth Place NW, Washington DC. 
- number of units - 199
- break down of units by number of bedrooms - NA
- subsidy history (timeline of when subsidies expire) 01/01/2023 (first ending) 09/01/2045 (last ending
- reac inspection score - 93c (2013)
- reac inspection history - see pdf

Neighborhood-level information:
- number of metros and bus routes within x miles (for now x can be 0.5 miles) - 13 number of metros and bus routes withing .5 miles. They are: Tenleytown Metro (.3 miles), 30N, 30S, 31, 33, S2 (.2 miles), 92, H2, H3, H4, M4, W45, W47 (.3 miles)
- number of subsidized units within x miles - 1 subsidized building within 1 mile, 15 units (Kennedy Institute)

- average market rent - *median* rent was $1,358 in 2009 and "$2,000+" in 2014 (47% increase) per the American Community Survey. Note they suppress the amount above $2,000
- median income: Average family income in Census Tract, 2014: $218,708  ([Neighborhood Info](http://www.neighborhoodinfodc.org/nclusters/Nbr_prof_clusb11.html))
- % residents at 50% AMI - substitute Poverty Rate, 2015: 3.6% (+- 3.2% error margin), 2012: 5.9% (+- 2.8 % error margin)
- % unemployment - Unemployment Rate 2014: 2.4%
- Building permits: There were 61 building permits within 0.25 miles issued in the last 3 months (very very roughly calculated). See the tab-delimited file dump here.
- PUD zoning applications filed: Change this to "Active PUD Applications" for now.  [Go to this page](https://app.dcoz.dc.gov/Content/Search/Search.aspx). Type 3E into the search box and click ANC active cases (they don't provide a direct link to search results). There are 22 active PUD cases in the ANC. This is a good example of a PUD at [4700 Wisconsin](https://app.dcoz.dc.gov/Content/Search/ViewCaseReport.aspx?case_id=18839), just a couple blocks away - you can put this one at the top of the list. 
- breakdown of residents: we don't have, might not be available....

**Comment by txomashernandez** [comment]
Much appreciated! This looks great, and hopefully includes everything that
we need for the building view.

-Thomas

**Comment by txomashernandez** [comment]
Hey team, 

For us to continue to use and refine, a draft style guide for colors and fonts across prototype pages. Happy to make changes as needed!

https://app.frontify.com/d/bzmigF5Rncdy/housing-insights-style-guide

**Comment by NealHumphrey** [comment]
Yay closing this issue! Will migrate some of the resource type stuff over to the next one as needed.
