### ISSUE TITLE
Demo connection of CKAN API to insights-site with Preservation Catalog sample data

### ISSUE THREAD

**Issue by NealHumphrey** [codefordc/housing-insights#5]
We have a flat-file dump of the Preservation Catalog from April 2016, available for download as a zip file here:
https://s3.amazonaws.com/nhumphrey-misc/PresCat_Export_20160401.zip

The Code for DC CKAN site (http://data.codefordc.org/) provides a place to store this data set, and we should be able to enable the [CKAN DataStore Extension](http://docs.ckan.org/en/latest/maintaining/datastore.html) to provide us with a record-level API. 

Steps:
1. Upload the PresCat data to CKAN (start with the 'Project.csv' file as first test set). Create a group on CKAN for housing-insights data sets, and any other CKAN configuration to make it clear what the data set is (keep in mind this is not the current PresCat, it's a few months old - we'll need to figure out our update strategy later). 
2. Configure the DataStore settings so that we can read data from the dataset via an API. 
3. Any Create, Update, Delete API setting should be disabled - we only want to read via the api. 
4. Add javascript code to our `/insights-site` page that sucessfully queries this CKAN api. At a minimum, return a single properties full record (by passing an ID) and a list of all property IDs. 
5. Demonstrate additional filter/query methods so future development can see how to use the api. 

Merge ready as soon as the minimum 2 API demos (property and property_list) are successfully able to display data on the insights-site page.

**Comment by mkalish** [comment]
@NealHumphrey 
data.codefordc.org is actually already set up with the Datastore so you should be good to go.  I can create an organization for the project and add you to it.  Let me know when register for an account.

**Comment by mkalish** [comment]
Additionally, we have some experience creating Lambda jobs in AWS to continuously push new data.

**Comment by mkalish** [comment]
Alright, the organization has been created and I've made you an admin of it.

Let me take a look at the data.  The CKAN datastore API can be used as a passthrough to the underlying databases, so JOINs are possible.  However, if the every query is going to involve a JOIN it might be easier to upload de-normalized data.  Do you have an example query?

**Comment by NealHumphrey** [comment]
Hey @mkalish sorry for delay. We'll typically be accessing the data via the 'project' table, but for example the subsidy table and reac_score tables are one-to-many (project to other). Typically there's not more than 2-5 records in each of those tables per property. 

So a common search might be `SELECT * FROM projects LEFT JOIN subsidy' WHERE subsidy.program = "DC housing production trust fund"` for example. 

For now it's TBD how common this will be - it depends what our actual final visualization/searches are. At a minimum I think that any time there is one-to-one relationship of propertyto other data, or any time we know there is at max just a couple entries (i.e. subsidy1, subsidy2) we can add it in to the primary table to avoid joins in the queries.

**Comment by mkalish** [comment]
Thats definitely something that CKAN can support and if its not going to be that often we can figure out some sort of caching situation.   A nice thing about CKAN is that any queries you're running against POSTGRES should translate nearly 1 to 1 to a CKAN query.

**Comment by NealHumphrey** [comment]
Note for future developers - the data tables for the April 2016 snapshot of the Preservation Catalog have been added to the data.codefordc.org CKAN site. This should be enough to use for now for demo connection purposes.

**Comment by NealHumphrey** [comment]
Closing this in favor of our API approach in #142
