### ISSUE TITLE
Create a Landing Page

### ISSUE THREAD

**Issue by louvis** [codefordc/housing-insights#504]
Create a landing page to introduce the tools to all users. It should be simple, clean and address the following questions:

- Who's the tool for?
- What can you do with the tool?
- Where did the data come from?

**Comment by jmithani** [comment]
If there is copy/style for me to follow, I might be able to tackle this. I'm not in DC anymore, but if working remote isn't an issue I can take a stab.

**Comment by louvis** [comment]
@jmithani I started to create a markdown file for this but only got a skeleton so far. If you want to work from it here's what I started.
```
---
layout: main
title: Adding Data Sources
---

#Who is this for?
This data tool is designed for affordable housing advocates and government officials to better understand the state of affordable housing in Washington, DC.

#What can it do?
The tool provides a dyamic view of all affordable housing in the city that can be filtered down to generate targeted insights and analysis.

#Where is the data from?
Data has been gathered from multiple sources including the DC Governement, Urban Institue, HUD, and the US Census Bureau. A full listing of data sources is located [here](http://example.com).
```

**Comment by NealHumphrey** [comment]
I did this in PR #549 .

**Comment by NealHumphrey** [comment]
@louvis I pretty muched used your text directly
