### ISSUE TITLE
Null data breaks some map view functionality

### ISSUE THREAD

**Issue by NealHumphrey** [codefordc/housing-insights#514]
Our newest data update has some null values for fields that we are using in the map view, most notably latitude and longitude but also other geocoded stuff like Ward. We haven't had null data before so haven't properly handled these. 

- Null lat/lon means clicking on an entry from the list of "matching projects" from the list on the right zooms you to the project location off the coast of Africa. 
- Ward-level bar chart of filtered data does not show up because results-view.js summary stats code breaks due to missing ward data. 
- Maybe others. 

Should fix and handle these.

**Comment by ostermanj** [comment]
Adressed in PR #517 

But issues remains: why do projects with know addresses have null lat/lin?
