### ISSUE TITLE
Core D3 scaffolding

### ISSUE THREAD

**Issue by NealHumphrey** [codefordc/housing-insights#52]
Let's all work through some D3 tutorials, and then set up the core functionality of our D3 websites. Feel free to split this into several separate tickets when it makes sense. 

*  Demo basic d3 functions (binding data, displaying it in views, updating data based on a user selection, using transformations)
* Demo connecting to data (flat files, and the CKAN api as noted in issue #5)
* Robust web-app Javascript structure that we can maintain long-term. We don't have to use the constructor pattern, but this has been recommended as a good technique for D3 apps that have lots of interacting parts.
* A couple basic unit tests 

Resources:
* A good clean basic D3 intro: http://alignedleft.com/tutorials/d3/
* Using the Constructor pattern in a D3 app: [Chris Given tutorial](https://github.com/JHU-DataViz-Summer16/week-6-class-demo/commits/master) (*see the 'Refactor chart into a constructor' commit in particular)
* App-style example using a setup-resize-update pattern, another well documented tutorial: [Gap Re-Minder](https://github.com/cmgiven/gap-reminder)
* The Constructor pattern generally: [Essential Design Patterns](https://addyosmani.com/resources/essentialjsdesignpatterns/book/#constructorpatternjavascript)
* Reusable charts in D3 - we should try to implement individual components like this, so that we can re-use them in different views (for example, using a donut chart for showing the percentages of each bedroom # in a building on both a search result page and on the building page itself). Basically, use custom getter/setter methods that return the object itself, to allow method chaining the same way the rest of D3 works: https://bost.ocks.org/mike/chart/

**Comment by ostermanj** [comment]
Here's the JSFiddle from Tuesday, using simple placeholder data : http://jsfiddle.net/ostermanj/h8xutLtr/26/

And an updated one using raw CSV from the repo showing, as an example, number of occupied units by cluster, sorted in descending order and with a bare-bones browser native tooltip. 

The viz looks less interesting when it's sorted by the primary dimension (just looks like a gradient). Would be best to sort by one dimension and color-code another.
http://jsfiddle.net/ostermanj/h8xutLtr/28/

**Comment by NealHumphrey** [comment]
@ostermanj I agree re: gradient. For now let's leave that to the prototype. In the prototype group we already discussed changing the behavior of this first screen to use a binary color scale w/ slider instead of the gradient - that way it behaves more consistently like the other color-coding options. 

I'd suggest these as individual tasks in roughly increasing complexity. Maybe we make a Fiddle for each of them? Let us know if you're claiming one, and add the fiddle link even if its a WIP

[ ] Refactor the blocks example as v4 D3
[ ] Add a slider to color code the blocks based on slider value. Slider min is min of the data, slider max is max of the data, blocks are sorted based on value. Color is gray for above value, blue for below value. 
[ ] Make a donut chart of bedroom count using a reusable function structure, as described in the resources above. Implement the chart twice as both a small icon and a large version.
[ ] Make a simple chart ( like a fake bar chart with an 'update random values' function) and try using the constructor pattern to run it using the setup, resize, update, resize lifecycle

**Comment by ostermanj** [comment]
Ok - I took the easier one and refactored the blocks to v4 — just a few changes needed, including loading the library as an external resource since JSFiddle doesn't have it built in. http://jsfiddle.net/ostermanj/h8xutLtr/29/

**Comment by ostermanj** [comment]
Here's an updated fiddle using a constructor and separating out some concerns. Was thinking of moving toward a model-controller-view way because it's what I'm trying to practice in general, but maybe it's overkill for this exercise, and I wasn't sure how well it would mesh with d3's way of doing things.
http://jsfiddle.net/ostermanj/h8xutLtr/35/

**Comment by ostermanj** [comment]
Link to d3 v4 - compatible d3-tip library https://github.com/VACLab/d3-tip

loading this would allow us to easily include tooltips on hovers

the data source would need to have human-readable name of each field for use in the tooltip, and elsewhere so we don't have to hard-code it in

**Comment by ostermanj** [comment]
moved jsfiddle work into a git repo basically recreating the steps above in separate commits
https://github.com/codefordc/housing-insights/pull/57

**Comment by ostermanj** [comment]
moved the d3-scaffolding folder into the [/docs/d3-mockup](https://github.com/codefordc/housing-insights/tree/dev/docs/d3-mockup) folder of the repository, which is the codebase for the jekyll site. committed on dev branch. if you clone or pull, the prototype page is available locally at {{host}}/d3-mockup/ (using jekyll serve http://127.0.0.1:4000/d3-mockup/)

**Comment by ostermanj** [comment]
new commit https://github.com/codefordc/housing-insights/tree/6eb24a6b530f75ab76fa41e3e28f4ade31aadecf on dev branch refactors the code into an IIFE wrapper with more modular design, setting up init() with update() and resize() placeholders. still need to merge in the slider and API call to CKAN that others have worked on. Probably best at this point actually to rewrite it in rather than attempt a merge since the design pattern has changed a lot.

**Comment by ostermanj** [comment]
series of commits  pushed to dev branch ending with [this one ](https://github.com/codefordc/housing-insights/commit/7454d3cf085bcdb1f424a3dd930d65a9974cce73) adds animated resorting functions, connects the viz to projects.csv data to better match the prototype, and puts in an initial fade-in. 

Earlier examples (the jsfiddle embeds) are now in subdirectory /d3-mockup/earlier. All the load-time effort was making the initial fade-in animation janky.

I'll make a pull request for someone else to merge into master—might as well have it live!

**Comment by NealHumphrey** [comment]
Cool, I'll review the request and do some quick testing to make sure it all looks like it's working. Thanks @ostermanj

**Comment by ostermanj** [comment]
@ptgott @wassona @vincecampanale I'm not sure I like this better, but in a new [without-extendPrototype](https://github.com/codefordc/housing-insights/commits/without-extendPrototype) branch I have functions added to the MovingBlock prototype without the helper function. It's maybe a little more verbose this way, which assigns each addition property via dot notation = ...  but the exercise helped me understand what was going on.

**Comment by ptgott** [comment]
I'm going to get started on incorporating something resembling the 'metrics' menu from the mockup into the chart, changing the field that maps across the range. I'll spend some time on it today and have something to show by the end of tomorrow.

**Comment by ostermanj** [comment]
thanks @ptgott. That all looks good. I pulled your branch into dev and then pushed some small changes. I didn't have time to get to your action items, but did update the styling and fixed some small bugs having to do with isNaN values. I'll paste your original note from the pull request below so we have it handy, with a couple responses:

> I've done a bit of work on making the moving block chart prototype page resemble the original [mock-up](https://app.moqups.com/neal@nhumphrey.com/zeZOXaXpNx/view/page/abd7c6e09?ui=0). So far, I've focused on creating a 'METRICS' menu that changes the field of the block chart. In producing the menu, I've made some design decisions that probably have better alternatives. I've summarized them below. Let me know what you think and feel free to revamp.

> 1. I'm okay with the 'without extend prototype' branch, but have put off incorporating it in case it's still something we're talking about.

The extendProtoype function is nice so I would keep it even though I benefited from seeing how it would work without it. 

> 2. I've added the Metrics menu to 'prototype-1a.js'. If this file was intended only for testing out the d3 functionality (rather than implementing the mock-up in general), I'd be happy to move the increasingly complex UI into a new file.

I think this is fine.

> 3. I've produced the menu using a \<ul\> element to avoid the cross-browser issues that apparently exist with styling \<select\> elements. That said, we can still go with a \<select\> approach.

If we're concerned with accessibility issues, focusable elements, keyboard control, we may want to stick with \<button\> elements or \<select\>

> 4. The menu refreshes the 'field' of each chart by deleting the chart's <svg> element and children, then adding the chart again by calling the constructor. I found it simpler this way, but we could also look at assigning new fields to an existing d3 chart object.

I didn't get into this, but the change could be nicely animated if we can figure out how to change fields rather than deleting and remaking the chart.

> 5. Each Metric menu option stores an array of Chart arguments. The Metric instance then uses the array to create new Charts. This is because the MovingBlockChart constructor adds the chart to the page automatically when called. It's not possible to assign a Chart to a Metric menu option without adding the chart to the page. An alternative would be to add a ‘create’ or ‘render’ method to each Chart, so adding the chart to the page would not be part of the initialSetup/setup methods. Instead, the Chart itself would be assigned to the menu option.

Didn't get into this or the next two.

> 6. I’m adding a chart constructor to the arguments of the Metric constructor. This is to allow for assigning different kinds of charts to each Metric menu option. An alternative would be to assign not a constructor but an entire Chart object (similar to point 5).

> 7. I need a good way to create an object using both a constructor and 'apply()'. This way the Metric constructor can take the constructor for a Chart (i.e. MovingBlockChart or some other kind) as an argument and call that constructor with the array of Chart arguments.

**Comment by NealHumphrey** [comment]
@ptgott, @ostermanj  - I think we can close this issue. Is there anything we need out of here? I'm going to pull the list of D3 resources out to a page on the website, let me know anything else.

**Comment by ptgott** [comment]
I'm okay with closing this issue!
