### ISSUE TITLE
Sidebar doesn't fully reset URL encoding

### ISSUE THREAD

**Issue by NealHumphrey** [codefordc/housing-insights#535]
When the URL decoding encounters an encoded tool url without any parameters, it is not able to remove the 'Loading saved state' message:

URL format: `http://127.0.0.1:4000/tool/#/HI/`

Error message:
![image](https://user-images.githubusercontent.com/5642566/30336221-82e76dcc-97b2-11e7-8e41-519bb2bf9fb5.png)

How to recreate the error:
- load the /tool page
- Select the 'matching projects' sidebar, and then reselect the 'summary' tab. 
- Refresh the page

Clearing the active filters ('x' on the pillboxes) appears to remove the /HI/ portion of the url when no parameters remain; however, the sidebar doesn't behave this way. It's probably best to fix it on the decode, but could also fix the sidebar encoding to similarly remove the /HI/ portion when no encoding remains.

**Comment by NealHumphrey** [comment]
@ostermanj can you take this on? Should be quick fix.

**Comment by ostermanj** [comment]
Yeah, I'll take a look.

**Comment by ostermanj** [comment]
Closing
