### ISSUE TITLE
dateFilterControl should be month first

### ISSUE THREAD

**Issue by NealHumphrey** [codefordc/housing-insights#537]
The current date filter control is set up to have text fields in the format [day] / [month] / [year]. This is likely not intuitive to most US users who will expect mm/dd/yyyy. I did not realize it was day first until adding a new field that had days outside of the 1-12 range. 

Change order of input and make sure filter applies them properly. Add key somewhere (maybe small gray text below the fields) to indicate the proper order.

**Comment by ostermanj** [comment]
Will address this on top of PR #539 because it needs the #/HI path fix to work.
