### ISSUE TITLE
Clear all filters notworking

### ISSUE THREAD

**Issue by NealHumphrey** [codefordc/housing-insights#540]
In testing during meeting, on @ostermanj 's machine, the 'clear all filters' button was not working after adding a slider for total units.

**Comment by ostermanj** [comment]
This seems to only occur if you move a slider, clearing the show null values checkbox, but return the slider back to the original position before releasing. Relatedly: given such behavior from the user, the show null values checkbox probably should not clear (ie not clear when the slider is moved but release in the original position).

**Comment by NealHumphrey** [comment]
Further note - it also occurs if you move the slider, release, and then move the slider back to the original position and release again. So it's tied to the fact that the slider is already at the extremes. 

I suspect this has to do with the 'isTouched' method

**Comment by NealHumphrey** [comment]
Resolved in #579
