### ISSUE TITLE
Dedupe address match failing due to integer MAR IDs

### ISSUE THREAD

**Issue by NealHumphrey** [codefordc/housing-insights#583]
In the deduplication process when loading new projects from the DCHousing or DHCD data sets, we check for duplicates by looking up the MAR ID of each individual address that was parsed from the address records and then comparing it to the mar ids that we have in our proj_addre table of the database. In the proj_addre table we store the mar id as a string - in fact, anything that is "id-like" in our database we store as text/string so that unexpected conversion doesn't take place and for consistent comparison. 

However, during the deduplication process we are sometimes using an integer version of the mar_id. This is causing address matching to fail and resulting in duplicated projects in our database. The use of an integer mar id occurs in about 1/3 of the cases. 

The attached log file is the output of the QA logger that @jkwening added to our address matching process; this includes logs from a few duplicate runs of the code.  The attached Excel file is one section of that log file, corresponding to the run of the code used to create the current live database. The Excel file has been parsed into appropriate columns for easier analysis, with a new column added indicating whether the first mar_id was a string or integer. 

[proj_sources.log.txt](https://github.com/codefordc/housing-insights/files/1324771/proj_sources.log.txt)

[sorted-log-for-matching-2017-09-21.xlsx](https://github.com/codefordc/housing-insights/files/1324769/sorted-log-for-matching-2017-09-21.xlsx)

All of the address matching that used an integer version of the mar_id failed to find a match, while around 1/2 of the ones using strings found matches. This suggests ~150 potential duplicated projects. 

The most likely reason for this inconsistent use of data type is probably the difference between when we look up the mar_id directly from our database copy of the MAR vs. when we need to query the MAR API to get the mar id. 

Find the place in the code that is converting to integer and use a string for mar_id instead. Re-run the code and verify that all the mar_ids used are now strings, and see if the total number of projects is reduced due to identifying duplicated projects.

**Comment by jkwening** [comment]
Closing - I believe this was resolved in PR #591
