### ISSUE TITLE
Geographic Area Comparison - reference map

### ISSUE THREAD

**Issue by NealHumphrey** [codefordc/housing-insights#59]
Make a reference map so our data team can tell how closely our different areas align to each other. 

One map should be able to show the boundaries 
- [x] Neighborhood Clusters
- [x] Wards
- [x] Census Tracts
- [x] Zillow's neighborhood boundaries ([available for download](https://www.zillow.com/howto/api/neighborhood-boundaries.htm)

-Could use Mapbox and do it directly on a javascript map. 

Faster/dirty versions:
- Check on NeighborhoodInfoDC to see if they have something like this already
- geojson.io looks like it might be a quick easy tool for making this, especially for a non/beginner coder. 

At this stage this is just a reference map so that the data team can decide on a plan for how to handle different geographic areas, so quick and dirty is the name of the game.

**Comment by rmcarder** [comment]
I've added these to the Map View.html page with a toggle to show one or multiple at a time. Will commit it tonight.
