### ISSUE TITLE
Calculate metro and bus route distances

### ISSUE THREAD

**Issue by NealHumphrey** [codefordc/housing-insights#73]
Using Mapbox's [Python SDK](https://github.com/mapbox/mapbox-sdk-py), calculate the number of (a) metro stops and (b) bus *routes* within 0.5 miles walking distance of each building in the `project` table from our database. 

- num. of bus routes should be defined as a bus route that stops at a bus stop within the distance parameter. If there are two stops in the radius that stop at a particular
- This ticket can be ready-to-merge into our dev branch if it uses a hard-coded list of addresses/lat-lon pairs, or if it reads directly from the [csv file of projects](https://s3.amazonaws.com/housinginsights/raw/preservation_catalog/20160401/Project.csv) downloaded locally. Other tickets will be developing re-usable modules for reading data from our database. 
- Bus stops should use [WMATA's JSON API](https://developer.wmata.com/docs/services/54763629281d83086473f231/operations/5476362a281d830c946a3d6d)
- It will likely be necessary to call WMATA's API with the 0.5 mile crow-fly distance, and then filter that to any stops that are not actually available within the Mapbox-provided walking distance.

**Comment by salomoneb** [comment]
Very quickly grabbed the location data for [Metro stations](https://developer.wmata.com/docs/services/5476364f031f590f38092507/operations/5476364f031f5909e4fe3311) and [bus stops](https://developer.wmata.com/docs/services/54763629281d83086473f231/operations/5476362a281d830c946a3d6d/console)

[transport_data.zip](https://github.com/codefordc/housing-insights/files/771781/transport_data.zip)


.

**Comment by NealHumphrey** [comment]
Cool @salomoneb ! 

@prisalex came to the Code for DC hacknight and joined up on the project; she started looking into this then (but I'm guessing w/ amount of time available probably didn't get very far). We can coordinate on this tomorrow and see what help she needs.

**Comment by prisalex** [comment]
Hello there, was actually planning on working on this today.   I'll keep you all posted on progress...

**Comment by salomoneb** [comment]
Cool. If you didn't already see it, Mapbox's [Distance API](https://www.mapbox.com/api-documentation/?language=Python#distance) looks like it might be good for this.

**Comment by prisalex** [comment]
@NealHumphrey This is the output [csv](https://dl.dropboxusercontent.com/u/9114766/wmataDist.csv) for just one of the proj locations.   Let me know if this format matches what you want.  I wasn't sure if you wanted the bus lines themselves in the CSV.  In which case I can just concat them all in one cell or can split those out into individual lines. 

Also, I did try to use the Python SDK but had some problems using it so looked at the Mapbox API docs and they claim that the distance API isn't supported in the Python SDK.  See [here](https://www.mapbox.com/api-documentation/?language=Python#retrieve-directions).  So I went with the REST API, which had better docs anyway.  Let me know if that is an issue. 

I'll create a PR for my code once you approve the final CSV format...

**Comment by NealHumphrey** [comment]
Great @prisalex ! 

We do want the bus line(s) at each stop. Ultimately the most robust version we might want to display is:
- A map with all the bus stops and metro locations
- A list of the bus routes available at each stop
- The shortest distance a resident would have to walk to get to each bus line, and a list of all the bus lines available within X distance. 

To get this into SQL, the simplest normalized way is probably two tables:
- The table you already made
- Another table with station_id and bus_route with whatever relevant bus_route information comes along with it (go ahead and save whatever they give you to give us flexibility of what to display down the line)

REST API is all good, whatever works!
