### ISSUE TITLE
Adding an information page for individual buildings

### ISSUE THREAD

**Issue by ptgott** [codefordc/housing-insights#80]
@wassona @vincecampanale As we talked about on Tuesday, here's a separate Issue for coordinating our work on the building page. We can refer to this when making commits related to the building page.

One thing to think about is how we will bind the data relating to a given building, as loaded in the moving block diagram, to that building's page. We don't have to determine this until after we've produced the visualizations for the accordion. In the meantime, we could think about using a 'dummy_building.json' object to refer to, or integrating such an object into a .js file.

**Comment by vincecampanale** [comment]
I think 'dummy_building.json' is a solid solution for now. We could even get real data from our data set and populate `dummy_building` without that data.

**Comment by NealHumphrey** [comment]
Let us (data team) know what format works best for you for the data, and we can make sure our python scripts output it in that format! We can make a couple real buildings worth for you to work from, too.

**Comment by ptgott** [comment]
@hansak11 @vincecampanale @NealHumphrey @wassona @ostermanj @jeannejk
Here's a list of data fields, as we talked about. They all come from the prototype of the building information page. We can add to/edit this list as we work through the building page, find data sources etc!

### Coordinates of non-building things; used for determining what's near a building
Metro stops
Bus stops
PUD applications
Building permits
Buildings with affordable housing
### Information to include for a given building's page
Subsidy types (Sec 202, Sec 8, Sec 207/233) and when they expire
Non-profit owned
Number of units
Number of studios
Number of 1BRs
Years until next subsidy expires
REAC score
Address
Owner telephone
Tax assessment

**Comment by Jeannejk** [comment]
This is a first attempt at finding these datafields in the tables loaded into postgres. I found the source for some fields unclear, which I included in a notes column. For now I've been collecting the info in excel, but we can move it into a better format at the next meeting if needed.

[Data Field Sources.xlsx](https://github.com/codefordc/housing-insights/files/789048/Data.Field.Sources.xlsx)

**Comment by ptgott** [comment]
#109 
I've done a bit more work on the Mapbox part of the building information page. So far I've pulled data from Open Data DC (the 'Affordable Housing' dataset) for development purposes, in place of the old Projects.csv. I've added a layer in one Mapbox map for all affordable housing. I've also done some work on making the MapboxPortal constructor a bit more extensible. 
### Here are some things that are left to do in adding Mapbox maps to the building page:
1. Integrate the building page with the 'app.dataCollection' object
2. Restructure the code to accommodate multiple datasets (e.g. there's a geoJSON file for metro stops on the Open Data DC page that I'd like to use for development). There could be a slew of AJAX calls when the information page loads, with the loading of the Mapbox maps taking place after these have finished.
3. Add multiple Mapbox maps and adjust the MapboxPortal constructor to make this simpler and DRYer.
4. Find a way to store information about the selected building (i.e. the building the information page is about) when the page loads. Since the shift from the moving block chart to the information page happens through a synchronous request, maybe it's most feasible to use a templating engine on the server? Or just switch from the moving block chart to the building information page through AJAX requests and keep the building information in memory as this happens?
5. Use a library to calculate the distance in miles between two geospatial coordinate pairs (this is the key bit of information in the text area of each accordion panel).

**Comment by wassona** [comment]
I finished an initial version of the building subsidy timeline chart, but implemented it with a local flat data file rather than a dummy_building.json, so I need to get that together. Tonight at the Hacknight I'm planning to start on the accordion.
