### ISSUE TITLE
Create glossary of terms

### ISSUE THREAD

**Issue by NealHumphrey** [codefordc/housing-insights#94]

**Comment by NealHumphrey** [comment]
Create a glossary of preservation organizations, acronyms, and other jargon. 

Technical notes for adding it to the website:
Add it to the website under /resources/glossary
* Create a folder in /docs/resources called 'glossary'
* add a file called 'index.md' to the glossary folder
* Use the YAML front-matter from the /resources page as a starting point
* write the glossary in markdown syntax


Things to include:
TOPA
DOPA
DHCD
HPTF / Housing Production Trust Fund
All the subsidy types (group by federal vs. local?)
Inclusionary zoning
PUD (planned unit development... the broader umbrella for inclusionary zoning applications)

**Comment by thischrisoliver** [comment]
I made a Google doc in our folder for now and started listing terms and definitions. Anyone can add to it: https://docs.google.com/document/d/1Qres4NpH0E2e_vj1M39rBpJEIZQ67shr-OV_I3RXEM0/edit?usp=sharing

**Comment by NealHumphrey** [comment]
TODO: need to link this to the /resources page.

**Comment by NealHumphrey** [comment]
Assigning myself to edit the /resources page

**Comment by thischrisoliver** [comment]
@NealHumphrey I've completed the definitions.

**Comment by NealHumphrey** [comment]
@thischrisoliver Awesome! Great timing - lots of new people coming in can definitely use it. I'll post it to Slack and include it in Monday's newsletter.
