### ISSUE TITLE
Figure out cleaner structure and files that need cleaning

### ISSUE THREAD

**Issue by blw9u2012** [codefordc/housing-insights#98]
Identify the data sources that need to be cleaned, and create a design for which Cleaner objects need to be created and how they will inherit from each other to reuse methods.

**Comment by NealHumphrey** [comment]
@prisalex the places we've been collecting cleaning-needed information is on this ticket:
https://github.com/codefordc/housing-insights/issues/58

and to some degree in the Data Dictionary: 
https://docs.google.com/spreadsheets/d/1hhuCgOIYNXP1VovA8TXuBRIR0drDSLSlBQsUSk-MS2Y/edit#gid=0

**Comment by NealHumphrey** [comment]
Closing - we are now using this spreadsheet to track our current and desired data sources:
https://docs.google.com/spreadsheets/d/1ueWgrtzlMSKD5y8QF7Xdj3V_4v7xw_A8vwhLAAqaZys/edit

And #129 has a more specific next task for comparing user requested comparisons to our desired data list.
